// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example
{

    internal class SampleResponse1
    {
#pragma warning disable 0649

        public Eras eras;
        public Agents agents;
        public Statuses statuses;
        public Cats cats;
        public int updated;
        public Data data;

#pragma warning restore 0649

    }

}
