// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace CanIuse
{

    public class ItemInfo
    {
        public string title;
        public string description;
        public string spec;
        public string status;
        public Link[] links;
        
        // public List<object> bugs { get; set; }
        //public object[] bugs;


        public string[] categories;
        public Stats stats;
        public string notes;
        // public NotesByNum notes_by_num;
        public Dictionary<string, string> notes_by_num; // Key is integer ?

        public double usage_perc_y;
        public double usage_perc_a;
        public bool ucprefix;
        public string parent;
        public string keywords;
        public string ie_id;
        public string chrome_id;

        // public bool shown { get; set; }
        // public bool? shown;
    }

}
