// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace CanIuse
{

    public class Agents
    {
        public Ie ie;
        public Edge edge;
        public Firefox firefox;
        public Chrome chrome;
        public Safari safari;
        public Opera opera;
        public IosSaf ios_saf;
        public OpMini op_mini;
        public Android android;
        public Bb bb;
        public OpMob op_mob;
        public AndChr and_chr;
        public AndFf and_ff;
        public IeMob ie_mob;
        public AndUc and_uc;
    }

}
