// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace CanIuse
{

    public class AndUc
    {
        public string browser;
        public string abbr;
        public string prefix;
        public string type;
        public Dictionary<string, double> usage_global;
        public string[] versions;
        // public PrefixExceptions3 prefix_exceptions;
        public Dictionary<string, string> prefix_exceptions;
    }

}
