// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;

namespace CanIuse
{

    public class Cats
    {
        public string[] CSS;
        public string[] HTML5;

        [JsonProperty(PropertyName = "JS API")]
        public string[] JS_API;

        public string[] Other;
        public string[] SVG;
    }

}
