// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;


namespace CanIuse
{

    // Tools.Serialization.JSON.Deserialize<CanIuse.RegionData.RootObject>("");
    public class RootObject
    {
        //public Eras eras;
        public Dictionary<string, string> eras;
        public Agents agents;

        // public Statuses statuses;
        public Dictionary<string, string> statuses;
        
        public Cats cats;
        public int updated;
        // public Data data;
        public Dictionary<string, ItemInfo> data;

        public static void xxx()
        { 
        
        }


    }

}
