// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace CanIuse
{

    public class Stats
    {

        public Dictionary<string, string> ie;
        public Dictionary<string, string> edge;
        public Dictionary<string, string> firefox;
        public Dictionary<string, string> chrome;
        public Dictionary<string, string> safari;
        public Dictionary<string, string> opera;
        public Dictionary<string, string> ios_saf;
        public Dictionary<string, string> op_mini;
        public Dictionary<string, string> android;
        public Dictionary<string, string> bb;
        public Dictionary<string, string> op_mob;
        public Dictionary<string, string> and_chr;
        public Dictionary<string, string> and_ff;
        public Dictionary<string, string> ie_mob;
        public Dictionary<string, string> and_uc;
    }

}
