// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace CanIuse
{

    public class Statuses
    {
        public string rec;
        public string pr;
        public string cr;
        public string wd;
        public string ls;
        public string other;
        public string unoff;
    }

}
