// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace CanIuse
{

    public class VersionList
    {
        public string version;
        public double global_usage;
        public int era;
        public string prefix;
    }

}
