// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Android287
    {
#pragma warning disable 0649

        public string 2.1;
        public string 2.2;
        public string 2.3;
        public string 3;
        public string 4;
        public string 4.1;
        public string 4.2-4.3;
        public string 4.4;
        public string 4.4.3-4.4.4;
        public string 44;

#pragma warning restore 0649

    }

}
