// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class AndUc
    {
#pragma warning disable 0649

        public string browser;
        public string abbr;
        public string prefix;
        public string type;
        public UsageGlobal15 usage_global;
        public string[] versions;
        public PrefixExceptions3 prefix_exceptions;

#pragma warning restore 0649

    }

}
