// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Cats
    {
#pragma warning disable 0649

        public string[] CSS;
        public string[] HTML5;
        public string[] JS API;
        public string[] Other;
        public string[] SVG;

#pragma warning restore 0649

    }

}
