// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Eras
    {
#pragma warning disable 0649

        public string e-41;
        public string e-40;
        public string e-39;
        public string e-38;
        public string e-37;
        public string e-36;
        public string e-35;
        public string e-34;
        public string e-33;
        public string e-32;
        public string e-31;
        public string e-30;
        public string e-29;
        public string e-28;
        public string e-27;
        public string e-26;
        public string e-25;
        public string e-24;
        public string e-23;
        public string e-22;
        public string e-21;
        public string e-20;
        public string e-19;
        public string e-18;
        public string e-17;
        public string e-16;
        public string e-15;
        public string e-14;
        public string e-13;
        public string e-12;
        public string e-11;
        public string e-10;
        public string e-9;
        public string e-8;
        public string e-7;
        public string e-6;
        public string e-5;
        public string e-4;
        public string e-3;
        public string e-2;
        public string e-1;
        public string e0;
        public string e1;
        public string e2;
        public string e3;

#pragma warning restore 0649

    }

}
