// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Firefox20
    {
#pragma warning disable 0649

        public string 2;
        public string 3;
        public string 3.5;
        public string 3.6;
        public string 4;
        public string 5;
        public string 6;
        public string 7;
        public string 8;
        public string 9;
        public string 10;
        public string 11;
        public string 12;
        public string 13;
        public string 14;
        public string 15;
        public string 16;
        public string 17;
        public string 18;
        public string 19;
        public string 20;
        public string 21;
        public string 22;
        public string 23;
        public string 24;
        public string 25;
        public string 26;
        public string 27;
        public string 28;
        public string 29;
        public string 30;
        public string 31;
        public string 32;
        public string 33;
        public string 34;
        public string 35;
        public string 36;
        public string 37;
        public string 38;
        public string 39;
        public string 40;
        public string 41;
        public string 42;
        public string 43;

#pragma warning restore 0649

    }

}
