// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Firefox
    {
#pragma warning disable 0649

        public string browser;
        public string abbr;
        public string prefix;
        public string type;
        public UsageGlobal3 usage_global;
        public string[] versions;

#pragma warning restore 0649

    }

}
