// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Ie278
    {
#pragma warning disable 0649

        public string 5.5;
        public string 6;
        public string 7;
        public string 8;
        public string 9;
        public string 10;
        public string 11;

#pragma warning restore 0649

    }

}
