// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class IeMob17
    {
#pragma warning disable 0649

        public string 10;
        public string 11;

#pragma warning restore 0649

    }

}
