// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class IosSaf109
    {
#pragma warning disable 0649

        public string 3.2;
        public string 4.0-4.1;
        public string 4.2-4.3;
        public string 5.0-5.1;
        public string 6.0-6.1;
        public string 7.0-7.1;
        public string 8;
        public string 8.1-8.4;
        public string 9;

#pragma warning restore 0649

    }

}
