// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Opera75
    {
#pragma warning disable 0649

        public string 9;
        public string 9.5-9.6;
        public string 10.0-10.1;
        public string 10.5;
        public string 10.6;
        public string 11;
        public string 11.1;
        public string 11.5;
        public string 11.6;
        public string 12;
        public string 12.1;
        public string 15;
        public string 16;
        public string 17;
        public string 18;
        public string 19;
        public string 20;
        public string 21;
        public string 22;
        public string 23;
        public string 24;
        public string 25;
        public string 26;
        public string 27;
        public string 28;
        public string 29;
        public string 30;
        public string 31;
        public string 32;
        public string 33;

#pragma warning restore 0649

    }

}
