// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Opera
    {
#pragma warning disable 0649

        public string browser;
        public string abbr;
        public string prefix;
        public string type;
        public UsageGlobal6 usage_global;
        public string[] versions;
        public PrefixExceptions prefix_exceptions;

#pragma warning restore 0649

    }

}
