// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class OpMob187
    {
#pragma warning disable 0649

        public string 10;
        public string 11;
        public string 11.1;
        public string 11.5;
        public string 12;
        public string 12.1;
        public string 30;

#pragma warning restore 0649

    }

}
