// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class PrefixExceptions
    {
#pragma warning disable 0649

        public string 9;
        public string 9.5-9.6;
        public string 10.0-10.1;
        public string 10.5;
        public string 10.6;
        public string 11;
        public string 11.1;
        public string 11.5;
        public string 11.6;
        public string 12;
        public string 12.1;

#pragma warning restore 0649

    }

}
