// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Safari24
    {
#pragma warning disable 0649

        public string 3.1;
        public string 3.2;
        public string 4;
        public string 5;
        public string 5.1;
        public string 6;
        public string 6.1;
        public string 7;
        public string 7.1;
        public string 8;
        public string 9;

#pragma warning restore 0649

    }

}
