// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class ScriptDefer
    {
#pragma warning disable 0649

        public string title;
        public string description;
        public string spec;
        public string status;
        public Link122[] links;
        public string[] categories;
        public Stats122 stats;
        public string notes;
        public NotesByNum122 notes_by_num;
        public double usage_perc_y;
        public double usage_perc_a;
        public bool ucprefix;
        public string parent;
        public string keywords;
        public string ie_id;
        public string chrome_id;

#pragma warning restore 0649

    }

}
