// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats36
    {
#pragma warning disable 0649

        public Ie37 ie;
        public Edge37 edge;
        public Firefox37 firefox;
        public Chrome37 chrome;
        public Safari37 safari;
        public Opera37 opera;
        public IosSaf37 ios_saf;
        public OpMini37 op_mini;
        public Android37 android;
        public Bb37 bb;
        public OpMob37 op_mob;
        public AndChr37 and_chr;
        public AndFf37 and_ff;
        public IeMob37 ie_mob;
        public AndUc37 and_uc;

#pragma warning restore 0649

    }

}
