// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats260
    {
#pragma warning disable 0649

        public Ie261 ie;
        public Edge261 edge;
        public Firefox261 firefox;
        public Chrome261 chrome;
        public Safari261 safari;
        public Opera261 opera;
        public IosSaf261 ios_saf;
        public OpMini261 op_mini;
        public Android261 android;
        public Bb261 bb;
        public OpMob261 op_mob;
        public AndChr261 and_chr;
        public AndFf261 and_ff;
        public IeMob261 ie_mob;
        public AndUc261 and_uc;

#pragma warning restore 0649

    }

}
