// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats207
    {
#pragma warning disable 0649

        public Ie208 ie;
        public Edge208 edge;
        public Firefox208 firefox;
        public Chrome208 chrome;
        public Safari208 safari;
        public Opera208 opera;
        public IosSaf208 ios_saf;
        public OpMini208 op_mini;
        public Android208 android;
        public Bb208 bb;
        public OpMob208 op_mob;
        public AndChr208 and_chr;
        public AndFf208 and_ff;
        public IeMob208 ie_mob;
        public AndUc208 and_uc;

#pragma warning restore 0649

    }

}
