// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats31
    {
#pragma warning disable 0649

        public Ie32 ie;
        public Edge32 edge;
        public Firefox32 firefox;
        public Chrome32 chrome;
        public Safari32 safari;
        public Opera32 opera;
        public IosSaf32 ios_saf;
        public OpMini32 op_mini;
        public Android32 android;
        public Bb32 bb;
        public OpMob32 op_mob;
        public AndChr32 and_chr;
        public AndFf32 and_ff;
        public IeMob32 ie_mob;
        public AndUc32 and_uc;

#pragma warning restore 0649

    }

}
