// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats115
    {
#pragma warning disable 0649

        public Ie116 ie;
        public Edge116 edge;
        public Firefox116 firefox;
        public Chrome116 chrome;
        public Safari116 safari;
        public Opera116 opera;
        public IosSaf116 ios_saf;
        public OpMini116 op_mini;
        public Android116 android;
        public Bb116 bb;
        public OpMob116 op_mob;
        public AndChr116 and_chr;
        public AndFf116 and_ff;
        public IeMob116 ie_mob;
        public AndUc116 and_uc;

#pragma warning restore 0649

    }

}
