// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats65
    {
#pragma warning disable 0649

        public Ie66 ie;
        public Edge66 edge;
        public Firefox66 firefox;
        public Chrome66 chrome;
        public Safari66 safari;
        public Opera66 opera;
        public IosSaf66 ios_saf;
        public OpMini66 op_mini;
        public Android66 android;
        public Bb66 bb;
        public OpMob66 op_mob;
        public AndChr66 and_chr;
        public AndFf66 and_ff;
        public IeMob66 ie_mob;
        public AndUc66 and_uc;

#pragma warning restore 0649

    }

}
