// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats289
    {
#pragma warning disable 0649

        public Ie290 ie;
        public Edge290 edge;
        public Firefox290 firefox;
        public Chrome290 chrome;
        public Safari290 safari;
        public Opera290 opera;
        public IosSaf290 ios_saf;
        public OpMini290 op_mini;
        public Android290 android;
        public Bb290 bb;
        public OpMob290 op_mob;
        public AndChr290 and_chr;
        public AndFf290 and_ff;
        public IeMob290 ie_mob;
        public AndUc290 and_uc;

#pragma warning restore 0649

    }

}
