// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats97
    {
#pragma warning disable 0649

        public Ie98 ie;
        public Edge98 edge;
        public Firefox98 firefox;
        public Chrome98 chrome;
        public Safari98 safari;
        public Opera98 opera;
        public IosSaf98 ios_saf;
        public OpMini98 op_mini;
        public Android98 android;
        public Bb98 bb;
        public OpMob98 op_mob;
        public AndChr98 and_chr;
        public AndFf98 and_ff;
        public IeMob98 ie_mob;
        public AndUc98 and_uc;

#pragma warning restore 0649

    }

}
