// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats71
    {
#pragma warning disable 0649

        public Ie72 ie;
        public Edge72 edge;
        public Firefox72 firefox;
        public Chrome72 chrome;
        public Safari72 safari;
        public Opera72 opera;
        public IosSaf72 ios_saf;
        public OpMini72 op_mini;
        public Android72 android;
        public Bb72 bb;
        public OpMob72 op_mob;
        public AndChr72 and_chr;
        public AndFf72 and_ff;
        public IeMob72 ie_mob;
        public AndUc72 and_uc;

#pragma warning restore 0649

    }

}
