// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats101
    {
#pragma warning disable 0649

        public Ie102 ie;
        public Edge102 edge;
        public Firefox102 firefox;
        public Chrome102 chrome;
        public Safari102 safari;
        public Opera102 opera;
        public IosSaf102 ios_saf;
        public OpMini102 op_mini;
        public Android102 android;
        public Bb102 bb;
        public OpMob102 op_mob;
        public AndChr102 and_chr;
        public AndFf102 and_ff;
        public IeMob102 ie_mob;
        public AndUc102 and_uc;

#pragma warning restore 0649

    }

}
