// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats61
    {
#pragma warning disable 0649

        public Ie62 ie;
        public Edge62 edge;
        public Firefox62 firefox;
        public Chrome62 chrome;
        public Safari62 safari;
        public Opera62 opera;
        public IosSaf62 ios_saf;
        public OpMini62 op_mini;
        public Android62 android;
        public Bb62 bb;
        public OpMob62 op_mob;
        public AndChr62 and_chr;
        public AndFf62 and_ff;
        public IeMob62 ie_mob;
        public AndUc62 and_uc;

#pragma warning restore 0649

    }

}
