// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats2
    {
#pragma warning disable 0649

        public Ie3 ie;
        public Edge3 edge;
        public Firefox3 firefox;
        public Chrome3 chrome;
        public Safari3 safari;
        public Opera3 opera;
        public IosSaf3 ios_saf;
        public OpMini3 op_mini;
        public Android3 android;
        public Bb3 bb;
        public OpMob3 op_mob;
        public AndChr3 and_chr;
        public AndFf3 and_ff;
        public IeMob3 ie_mob;
        public AndUc3 and_uc;

#pragma warning restore 0649

    }

}
