// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats146
    {
#pragma warning disable 0649

        public Ie147 ie;
        public Edge147 edge;
        public Firefox147 firefox;
        public Chrome147 chrome;
        public Safari147 safari;
        public Opera147 opera;
        public IosSaf147 ios_saf;
        public OpMini147 op_mini;
        public Android147 android;
        public Bb147 bb;
        public OpMob147 op_mob;
        public AndChr147 and_chr;
        public AndFf147 and_ff;
        public IeMob147 ie_mob;
        public AndUc147 and_uc;

#pragma warning restore 0649

    }

}
