// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats222
    {
#pragma warning disable 0649

        public Ie223 ie;
        public Edge223 edge;
        public Firefox223 firefox;
        public Chrome223 chrome;
        public Safari223 safari;
        public Opera223 opera;
        public IosSaf223 ios_saf;
        public OpMini223 op_mini;
        public Android223 android;
        public Bb223 bb;
        public OpMob223 op_mob;
        public AndChr223 and_chr;
        public AndFf223 and_ff;
        public IeMob223 ie_mob;
        public AndUc223 and_uc;

#pragma warning restore 0649

    }

}
