// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats6
    {
#pragma warning disable 0649

        public Ie7 ie;
        public Edge7 edge;
        public Firefox7 firefox;
        public Chrome7 chrome;
        public Safari7 safari;
        public Opera7 opera;
        public IosSaf7 ios_saf;
        public OpMini7 op_mini;
        public Android7 android;
        public Bb7 bb;
        public OpMob7 op_mob;
        public AndChr7 and_chr;
        public AndFf7 and_ff;
        public IeMob7 ie_mob;
        public AndUc7 and_uc;

#pragma warning restore 0649

    }

}
