// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats62
    {
#pragma warning disable 0649

        public Ie63 ie;
        public Edge63 edge;
        public Firefox63 firefox;
        public Chrome63 chrome;
        public Safari63 safari;
        public Opera63 opera;
        public IosSaf63 ios_saf;
        public OpMini63 op_mini;
        public Android63 android;
        public Bb63 bb;
        public OpMob63 op_mob;
        public AndChr63 and_chr;
        public AndFf63 and_ff;
        public IeMob63 ie_mob;
        public AndUc63 and_uc;

#pragma warning restore 0649

    }

}
