// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats105
    {
#pragma warning disable 0649

        public Ie106 ie;
        public Edge106 edge;
        public Firefox106 firefox;
        public Chrome106 chrome;
        public Safari106 safari;
        public Opera106 opera;
        public IosSaf106 ios_saf;
        public OpMini106 op_mini;
        public Android106 android;
        public Bb106 bb;
        public OpMob106 op_mob;
        public AndChr106 and_chr;
        public AndFf106 and_ff;
        public IeMob106 ie_mob;
        public AndUc106 and_uc;

#pragma warning restore 0649

    }

}
