// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats139
    {
#pragma warning disable 0649

        public Ie140 ie;
        public Edge140 edge;
        public Firefox140 firefox;
        public Chrome140 chrome;
        public Safari140 safari;
        public Opera140 opera;
        public IosSaf140 ios_saf;
        public OpMini140 op_mini;
        public Android140 android;
        public Bb140 bb;
        public OpMob140 op_mob;
        public AndChr140 and_chr;
        public AndFf140 and_ff;
        public IeMob140 ie_mob;
        public AndUc140 and_uc;

#pragma warning restore 0649

    }

}
