// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats208
    {
#pragma warning disable 0649

        public Ie209 ie;
        public Edge209 edge;
        public Firefox209 firefox;
        public Chrome209 chrome;
        public Safari209 safari;
        public Opera209 opera;
        public IosSaf209 ios_saf;
        public OpMini209 op_mini;
        public Android209 android;
        public Bb209 bb;
        public OpMob209 op_mob;
        public AndChr209 and_chr;
        public AndFf209 and_ff;
        public IeMob209 ie_mob;
        public AndUc209 and_uc;

#pragma warning restore 0649

    }

}
