// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats186
    {
#pragma warning disable 0649

        public Ie187 ie;
        public Edge187 edge;
        public Firefox187 firefox;
        public Chrome187 chrome;
        public Safari187 safari;
        public Opera187 opera;
        public IosSaf187 ios_saf;
        public OpMini187 op_mini;
        public Android187 android;
        public Bb187 bb;
        public OpMob187 op_mob;
        public AndChr187 and_chr;
        public AndFf187 and_ff;
        public IeMob187 ie_mob;
        public AndUc187 and_uc;

#pragma warning restore 0649

    }

}
