// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats129
    {
#pragma warning disable 0649

        public Ie130 ie;
        public Edge130 edge;
        public Firefox130 firefox;
        public Chrome130 chrome;
        public Safari130 safari;
        public Opera130 opera;
        public IosSaf130 ios_saf;
        public OpMini130 op_mini;
        public Android130 android;
        public Bb130 bb;
        public OpMob130 op_mob;
        public AndChr130 and_chr;
        public AndFf130 and_ff;
        public IeMob130 ie_mob;
        public AndUc130 and_uc;

#pragma warning restore 0649

    }

}
