// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats128
    {
#pragma warning disable 0649

        public Ie129 ie;
        public Edge129 edge;
        public Firefox129 firefox;
        public Chrome129 chrome;
        public Safari129 safari;
        public Opera129 opera;
        public IosSaf129 ios_saf;
        public OpMini129 op_mini;
        public Android129 android;
        public Bb129 bb;
        public OpMob129 op_mob;
        public AndChr129 and_chr;
        public AndFf129 and_ff;
        public IeMob129 ie_mob;
        public AndUc129 and_uc;

#pragma warning restore 0649

    }

}
