// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats74
    {
#pragma warning disable 0649

        public Ie75 ie;
        public Edge75 edge;
        public Firefox75 firefox;
        public Chrome75 chrome;
        public Safari75 safari;
        public Opera75 opera;
        public IosSaf75 ios_saf;
        public OpMini75 op_mini;
        public Android75 android;
        public Bb75 bb;
        public OpMob75 op_mob;
        public AndChr75 and_chr;
        public AndFf75 and_ff;
        public IeMob75 ie_mob;
        public AndUc75 and_uc;

#pragma warning restore 0649

    }

}
