// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats55
    {
#pragma warning disable 0649

        public Ie56 ie;
        public Edge56 edge;
        public Firefox56 firefox;
        public Chrome56 chrome;
        public Safari56 safari;
        public Opera56 opera;
        public IosSaf56 ios_saf;
        public OpMini56 op_mini;
        public Android56 android;
        public Bb56 bb;
        public OpMob56 op_mob;
        public AndChr56 and_chr;
        public AndFf56 and_ff;
        public IeMob56 ie_mob;
        public AndUc56 and_uc;

#pragma warning restore 0649

    }

}
