// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats30
    {
#pragma warning disable 0649

        public Ie31 ie;
        public Edge31 edge;
        public Firefox31 firefox;
        public Chrome31 chrome;
        public Safari31 safari;
        public Opera31 opera;
        public IosSaf31 ios_saf;
        public OpMini31 op_mini;
        public Android31 android;
        public Bb31 bb;
        public OpMob31 op_mob;
        public AndChr31 and_chr;
        public AndFf31 and_ff;
        public IeMob31 ie_mob;
        public AndUc31 and_uc;

#pragma warning restore 0649

    }

}
