// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats89
    {
#pragma warning disable 0649

        public Ie90 ie;
        public Edge90 edge;
        public Firefox90 firefox;
        public Chrome90 chrome;
        public Safari90 safari;
        public Opera90 opera;
        public IosSaf90 ios_saf;
        public OpMini90 op_mini;
        public Android90 android;
        public Bb90 bb;
        public OpMob90 op_mob;
        public AndChr90 and_chr;
        public AndFf90 and_ff;
        public IeMob90 ie_mob;
        public AndUc90 and_uc;

#pragma warning restore 0649

    }

}
