// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats221
    {
#pragma warning disable 0649

        public Ie222 ie;
        public Edge222 edge;
        public Firefox222 firefox;
        public Chrome222 chrome;
        public Safari222 safari;
        public Opera222 opera;
        public IosSaf222 ios_saf;
        public OpMini222 op_mini;
        public Android222 android;
        public Bb222 bb;
        public OpMob222 op_mob;
        public AndChr222 and_chr;
        public AndFf222 and_ff;
        public IeMob222 ie_mob;
        public AndUc222 and_uc;

#pragma warning restore 0649

    }

}
