// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats249
    {
#pragma warning disable 0649

        public Ie250 ie;
        public Edge250 edge;
        public Firefox250 firefox;
        public Chrome250 chrome;
        public Safari250 safari;
        public Opera250 opera;
        public IosSaf250 ios_saf;
        public OpMini250 op_mini;
        public Android250 android;
        public Bb250 bb;
        public OpMob250 op_mob;
        public AndChr250 and_chr;
        public AndFf250 and_ff;
        public IeMob250 ie_mob;
        public AndUc250 and_uc;

#pragma warning restore 0649

    }

}
