// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats231
    {
#pragma warning disable 0649

        public Ie232 ie;
        public Edge232 edge;
        public Firefox232 firefox;
        public Chrome232 chrome;
        public Safari232 safari;
        public Opera232 opera;
        public IosSaf232 ios_saf;
        public OpMini232 op_mini;
        public Android232 android;
        public Bb232 bb;
        public OpMob232 op_mob;
        public AndChr232 and_chr;
        public AndFf232 and_ff;
        public IeMob232 ie_mob;
        public AndUc232 and_uc;

#pragma warning restore 0649

    }

}
