// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats177
    {
#pragma warning disable 0649

        public Ie178 ie;
        public Edge178 edge;
        public Firefox178 firefox;
        public Chrome178 chrome;
        public Safari178 safari;
        public Opera178 opera;
        public IosSaf178 ios_saf;
        public OpMini178 op_mini;
        public Android178 android;
        public Bb178 bb;
        public OpMob178 op_mob;
        public AndChr178 and_chr;
        public AndFf178 and_ff;
        public IeMob178 ie_mob;
        public AndUc178 and_uc;

#pragma warning restore 0649

    }

}
