// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats165
    {
#pragma warning disable 0649

        public Ie166 ie;
        public Edge166 edge;
        public Firefox166 firefox;
        public Chrome166 chrome;
        public Safari166 safari;
        public Opera166 opera;
        public IosSaf166 ios_saf;
        public OpMini166 op_mini;
        public Android166 android;
        public Bb166 bb;
        public OpMob166 op_mob;
        public AndChr166 and_chr;
        public AndFf166 and_ff;
        public IeMob166 ie_mob;
        public AndUc166 and_uc;

#pragma warning restore 0649

    }

}
