// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats188
    {
#pragma warning disable 0649

        public Ie189 ie;
        public Edge189 edge;
        public Firefox189 firefox;
        public Chrome189 chrome;
        public Safari189 safari;
        public Opera189 opera;
        public IosSaf189 ios_saf;
        public OpMini189 op_mini;
        public Android189 android;
        public Bb189 bb;
        public OpMob189 op_mob;
        public AndChr189 and_chr;
        public AndFf189 and_ff;
        public IeMob189 ie_mob;
        public AndUc189 and_uc;

#pragma warning restore 0649

    }

}
