// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats8
    {
#pragma warning disable 0649

        public Ie9 ie;
        public Edge9 edge;
        public Firefox9 firefox;
        public Chrome9 chrome;
        public Safari9 safari;
        public Opera9 opera;
        public IosSaf9 ios_saf;
        public OpMini9 op_mini;
        public Android9 android;
        public Bb9 bb;
        public OpMob9 op_mob;
        public AndChr9 and_chr;
        public AndFf9 and_ff;
        public IeMob9 ie_mob;
        public AndUc9 and_uc;

#pragma warning restore 0649

    }

}
