// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats161
    {
#pragma warning disable 0649

        public Ie162 ie;
        public Edge162 edge;
        public Firefox162 firefox;
        public Chrome162 chrome;
        public Safari162 safari;
        public Opera162 opera;
        public IosSaf162 ios_saf;
        public OpMini162 op_mini;
        public Android162 android;
        public Bb162 bb;
        public OpMob162 op_mob;
        public AndChr162 and_chr;
        public AndFf162 and_ff;
        public IeMob162 ie_mob;
        public AndUc162 and_uc;

#pragma warning restore 0649

    }

}
