// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats286
    {
#pragma warning disable 0649

        public Ie287 ie;
        public Edge287 edge;
        public Firefox287 firefox;
        public Chrome287 chrome;
        public Safari287 safari;
        public Opera287 opera;
        public IosSaf287 ios_saf;
        public OpMini287 op_mini;
        public Android287 android;
        public Bb287 bb;
        public OpMob287 op_mob;
        public AndChr287 and_chr;
        public AndFf287 and_ff;
        public IeMob287 ie_mob;
        public AndUc287 and_uc;

#pragma warning restore 0649

    }

}
