// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats181
    {
#pragma warning disable 0649

        public Ie182 ie;
        public Edge182 edge;
        public Firefox182 firefox;
        public Chrome182 chrome;
        public Safari182 safari;
        public Opera182 opera;
        public IosSaf182 ios_saf;
        public OpMini182 op_mini;
        public Android182 android;
        public Bb182 bb;
        public OpMob182 op_mob;
        public AndChr182 and_chr;
        public AndFf182 and_ff;
        public IeMob182 ie_mob;
        public AndUc182 and_uc;

#pragma warning restore 0649

    }

}
