// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats217
    {
#pragma warning disable 0649

        public Ie218 ie;
        public Edge218 edge;
        public Firefox218 firefox;
        public Chrome218 chrome;
        public Safari218 safari;
        public Opera218 opera;
        public IosSaf218 ios_saf;
        public OpMini218 op_mini;
        public Android218 android;
        public Bb218 bb;
        public OpMob218 op_mob;
        public AndChr218 and_chr;
        public AndFf218 and_ff;
        public IeMob218 ie_mob;
        public AndUc218 and_uc;

#pragma warning restore 0649

    }

}
