// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats154
    {
#pragma warning disable 0649

        public Ie155 ie;
        public Edge155 edge;
        public Firefox155 firefox;
        public Chrome155 chrome;
        public Safari155 safari;
        public Opera155 opera;
        public IosSaf155 ios_saf;
        public OpMini155 op_mini;
        public Android155 android;
        public Bb155 bb;
        public OpMob155 op_mob;
        public AndChr155 and_chr;
        public AndFf155 and_ff;
        public IeMob155 ie_mob;
        public AndUc155 and_uc;

#pragma warning restore 0649

    }

}
