// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats81
    {
#pragma warning disable 0649

        public Ie82 ie;
        public Edge82 edge;
        public Firefox82 firefox;
        public Chrome82 chrome;
        public Safari82 safari;
        public Opera82 opera;
        public IosSaf82 ios_saf;
        public OpMini82 op_mini;
        public Android82 android;
        public Bb82 bb;
        public OpMob82 op_mob;
        public AndChr82 and_chr;
        public AndFf82 and_ff;
        public IeMob82 ie_mob;
        public AndUc82 and_uc;

#pragma warning restore 0649

    }

}
