// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats79
    {
#pragma warning disable 0649

        public Ie80 ie;
        public Edge80 edge;
        public Firefox80 firefox;
        public Chrome80 chrome;
        public Safari80 safari;
        public Opera80 opera;
        public IosSaf80 ios_saf;
        public OpMini80 op_mini;
        public Android80 android;
        public Bb80 bb;
        public OpMob80 op_mob;
        public AndChr80 and_chr;
        public AndFf80 and_ff;
        public IeMob80 ie_mob;
        public AndUc80 and_uc;

#pragma warning restore 0649

    }

}
