// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats10
    {
#pragma warning disable 0649

        public Ie11 ie;
        public Edge11 edge;
        public Firefox11 firefox;
        public Chrome11 chrome;
        public Safari11 safari;
        public Opera11 opera;
        public IosSaf11 ios_saf;
        public OpMini11 op_mini;
        public Android11 android;
        public Bb11 bb;
        public OpMob11 op_mob;
        public AndChr11 and_chr;
        public AndFf11 and_ff;
        public IeMob11 ie_mob;
        public AndUc11 and_uc;

#pragma warning restore 0649

    }

}
