// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats14
    {
#pragma warning disable 0649

        public Ie15 ie;
        public Edge15 edge;
        public Firefox15 firefox;
        public Chrome15 chrome;
        public Safari15 safari;
        public Opera15 opera;
        public IosSaf15 ios_saf;
        public OpMini15 op_mini;
        public Android15 android;
        public Bb15 bb;
        public OpMob15 op_mob;
        public AndChr15 and_chr;
        public AndFf15 and_ff;
        public IeMob15 ie_mob;
        public AndUc15 and_uc;

#pragma warning restore 0649

    }

}
