// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats280
    {
#pragma warning disable 0649

        public Ie281 ie;
        public Edge281 edge;
        public Firefox281 firefox;
        public Chrome281 chrome;
        public Safari281 safari;
        public Opera281 opera;
        public IosSaf281 ios_saf;
        public OpMini281 op_mini;
        public Android281 android;
        public Bb281 bb;
        public OpMob281 op_mob;
        public AndChr281 and_chr;
        public AndFf281 and_ff;
        public IeMob281 ie_mob;
        public AndUc281 and_uc;

#pragma warning restore 0649

    }

}
