// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats116
    {
#pragma warning disable 0649

        public Ie117 ie;
        public Edge117 edge;
        public Firefox117 firefox;
        public Chrome117 chrome;
        public Safari117 safari;
        public Opera117 opera;
        public IosSaf117 ios_saf;
        public OpMini117 op_mini;
        public Android117 android;
        public Bb117 bb;
        public OpMob117 op_mob;
        public AndChr117 and_chr;
        public AndFf117 and_ff;
        public IeMob117 ie_mob;
        public AndUc117 and_uc;

#pragma warning restore 0649

    }

}
