// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats45
    {
#pragma warning disable 0649

        public Ie46 ie;
        public Edge46 edge;
        public Firefox46 firefox;
        public Chrome46 chrome;
        public Safari46 safari;
        public Opera46 opera;
        public IosSaf46 ios_saf;
        public OpMini46 op_mini;
        public Android46 android;
        public Bb46 bb;
        public OpMob46 op_mob;
        public AndChr46 and_chr;
        public AndFf46 and_ff;
        public IeMob46 ie_mob;
        public AndUc46 and_uc;

#pragma warning restore 0649

    }

}
