// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats104
    {
#pragma warning disable 0649

        public Ie105 ie;
        public Edge105 edge;
        public Firefox105 firefox;
        public Chrome105 chrome;
        public Safari105 safari;
        public Opera105 opera;
        public IosSaf105 ios_saf;
        public OpMini105 op_mini;
        public Android105 android;
        public Bb105 bb;
        public OpMob105 op_mob;
        public AndChr105 and_chr;
        public AndFf105 and_ff;
        public IeMob105 ie_mob;
        public AndUc105 and_uc;

#pragma warning restore 0649

    }

}
