// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats157
    {
#pragma warning disable 0649

        public Ie158 ie;
        public Edge158 edge;
        public Firefox158 firefox;
        public Chrome158 chrome;
        public Safari158 safari;
        public Opera158 opera;
        public IosSaf158 ios_saf;
        public OpMini158 op_mini;
        public Android158 android;
        public Bb158 bb;
        public OpMob158 op_mob;
        public AndChr158 and_chr;
        public AndFf158 and_ff;
        public IeMob158 ie_mob;
        public AndUc158 and_uc;

#pragma warning restore 0649

    }

}
