// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats197
    {
#pragma warning disable 0649

        public Ie198 ie;
        public Edge198 edge;
        public Firefox198 firefox;
        public Chrome198 chrome;
        public Safari198 safari;
        public Opera198 opera;
        public IosSaf198 ios_saf;
        public OpMini198 op_mini;
        public Android198 android;
        public Bb198 bb;
        public OpMob198 op_mob;
        public AndChr198 and_chr;
        public AndFf198 and_ff;
        public IeMob198 ie_mob;
        public AndUc198 and_uc;

#pragma warning restore 0649

    }

}
