// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats256
    {
#pragma warning disable 0649

        public Ie257 ie;
        public Edge257 edge;
        public Firefox257 firefox;
        public Chrome257 chrome;
        public Safari257 safari;
        public Opera257 opera;
        public IosSaf257 ios_saf;
        public OpMini257 op_mini;
        public Android257 android;
        public Bb257 bb;
        public OpMob257 op_mob;
        public AndChr257 and_chr;
        public AndFf257 and_ff;
        public IeMob257 ie_mob;
        public AndUc257 and_uc;

#pragma warning restore 0649

    }

}
