// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats282
    {
#pragma warning disable 0649

        public Ie283 ie;
        public Edge283 edge;
        public Firefox283 firefox;
        public Chrome283 chrome;
        public Safari283 safari;
        public Opera283 opera;
        public IosSaf283 ios_saf;
        public OpMini283 op_mini;
        public Android283 android;
        public Bb283 bb;
        public OpMob283 op_mob;
        public AndChr283 and_chr;
        public AndFf283 and_ff;
        public IeMob283 ie_mob;
        public AndUc283 and_uc;

#pragma warning restore 0649

    }

}
