// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats124
    {
#pragma warning disable 0649

        public Ie125 ie;
        public Edge125 edge;
        public Firefox125 firefox;
        public Chrome125 chrome;
        public Safari125 safari;
        public Opera125 opera;
        public IosSaf125 ios_saf;
        public OpMini125 op_mini;
        public Android125 android;
        public Bb125 bb;
        public OpMob125 op_mob;
        public AndChr125 and_chr;
        public AndFf125 and_ff;
        public IeMob125 ie_mob;
        public AndUc125 and_uc;

#pragma warning restore 0649

    }

}
