// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats219
    {
#pragma warning disable 0649

        public Ie220 ie;
        public Edge220 edge;
        public Firefox220 firefox;
        public Chrome220 chrome;
        public Safari220 safari;
        public Opera220 opera;
        public IosSaf220 ios_saf;
        public OpMini220 op_mini;
        public Android220 android;
        public Bb220 bb;
        public OpMob220 op_mob;
        public AndChr220 and_chr;
        public AndFf220 and_ff;
        public IeMob220 ie_mob;
        public AndUc220 and_uc;

#pragma warning restore 0649

    }

}
