// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats5
    {
#pragma warning disable 0649

        public Ie6 ie;
        public Edge6 edge;
        public Firefox6 firefox;
        public Chrome6 chrome;
        public Safari6 safari;
        public Opera6 opera;
        public IosSaf6 ios_saf;
        public OpMini6 op_mini;
        public Android6 android;
        public Bb6 bb;
        public OpMob6 op_mob;
        public AndChr6 and_chr;
        public AndFf6 and_ff;
        public IeMob6 ie_mob;
        public AndUc6 and_uc;

#pragma warning restore 0649

    }

}
