// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats57
    {
#pragma warning disable 0649

        public Ie58 ie;
        public Edge58 edge;
        public Firefox58 firefox;
        public Chrome58 chrome;
        public Safari58 safari;
        public Opera58 opera;
        public IosSaf58 ios_saf;
        public OpMini58 op_mini;
        public Android58 android;
        public Bb58 bb;
        public OpMob58 op_mob;
        public AndChr58 and_chr;
        public AndFf58 and_ff;
        public IeMob58 ie_mob;
        public AndUc58 and_uc;

#pragma warning restore 0649

    }

}
