// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats292
    {
#pragma warning disable 0649

        public Ie293 ie;
        public Edge293 edge;
        public Firefox293 firefox;
        public Chrome293 chrome;
        public Safari293 safari;
        public Opera293 opera;
        public IosSaf293 ios_saf;
        public OpMini293 op_mini;
        public Android293 android;
        public Bb293 bb;
        public OpMob293 op_mob;
        public AndChr293 and_chr;
        public AndFf293 and_ff;
        public IeMob293 ie_mob;
        public AndUc293 and_uc;

#pragma warning restore 0649

    }

}
