// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats142
    {
#pragma warning disable 0649

        public Ie143 ie;
        public Edge143 edge;
        public Firefox143 firefox;
        public Chrome143 chrome;
        public Safari143 safari;
        public Opera143 opera;
        public IosSaf143 ios_saf;
        public OpMini143 op_mini;
        public Android143 android;
        public Bb143 bb;
        public OpMob143 op_mob;
        public AndChr143 and_chr;
        public AndFf143 and_ff;
        public IeMob143 ie_mob;
        public AndUc143 and_uc;

#pragma warning restore 0649

    }

}
