// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats185
    {
#pragma warning disable 0649

        public Ie186 ie;
        public Edge186 edge;
        public Firefox186 firefox;
        public Chrome186 chrome;
        public Safari186 safari;
        public Opera186 opera;
        public IosSaf186 ios_saf;
        public OpMini186 op_mini;
        public Android186 android;
        public Bb186 bb;
        public OpMob186 op_mob;
        public AndChr186 and_chr;
        public AndFf186 and_ff;
        public IeMob186 ie_mob;
        public AndUc186 and_uc;

#pragma warning restore 0649

    }

}
