// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats175
    {
#pragma warning disable 0649

        public Ie176 ie;
        public Edge176 edge;
        public Firefox176 firefox;
        public Chrome176 chrome;
        public Safari176 safari;
        public Opera176 opera;
        public IosSaf176 ios_saf;
        public OpMini176 op_mini;
        public Android176 android;
        public Bb176 bb;
        public OpMob176 op_mob;
        public AndChr176 and_chr;
        public AndFf176 and_ff;
        public IeMob176 ie_mob;
        public AndUc176 and_uc;

#pragma warning restore 0649

    }

}
