// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats121
    {
#pragma warning disable 0649

        public Ie122 ie;
        public Edge122 edge;
        public Firefox122 firefox;
        public Chrome122 chrome;
        public Safari122 safari;
        public Opera122 opera;
        public IosSaf122 ios_saf;
        public OpMini122 op_mini;
        public Android122 android;
        public Bb122 bb;
        public OpMob122 op_mob;
        public AndChr122 and_chr;
        public AndFf122 and_ff;
        public IeMob122 ie_mob;
        public AndUc122 and_uc;

#pragma warning restore 0649

    }

}
