// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats248
    {
#pragma warning disable 0649

        public Ie249 ie;
        public Edge249 edge;
        public Firefox249 firefox;
        public Chrome249 chrome;
        public Safari249 safari;
        public Opera249 opera;
        public IosSaf249 ios_saf;
        public OpMini249 op_mini;
        public Android249 android;
        public Bb249 bb;
        public OpMob249 op_mob;
        public AndChr249 and_chr;
        public AndFf249 and_ff;
        public IeMob249 ie_mob;
        public AndUc249 and_uc;

#pragma warning restore 0649

    }

}
