// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats191
    {
#pragma warning disable 0649

        public Ie192 ie;
        public Edge192 edge;
        public Firefox192 firefox;
        public Chrome192 chrome;
        public Safari192 safari;
        public Opera192 opera;
        public IosSaf192 ios_saf;
        public OpMini192 op_mini;
        public Android192 android;
        public Bb192 bb;
        public OpMob192 op_mob;
        public AndChr192 and_chr;
        public AndFf192 and_ff;
        public IeMob192 ie_mob;
        public AndUc192 and_uc;

#pragma warning restore 0649

    }

}
