// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats287
    {
#pragma warning disable 0649

        public Ie288 ie;
        public Edge288 edge;
        public Firefox288 firefox;
        public Chrome288 chrome;
        public Safari288 safari;
        public Opera288 opera;
        public IosSaf288 ios_saf;
        public OpMini288 op_mini;
        public Android288 android;
        public Bb288 bb;
        public OpMob288 op_mob;
        public AndChr288 and_chr;
        public AndFf288 and_ff;
        public IeMob288 ie_mob;
        public AndUc288 and_uc;

#pragma warning restore 0649

    }

}
