// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats86
    {
#pragma warning disable 0649

        public Ie87 ie;
        public Edge87 edge;
        public Firefox87 firefox;
        public Chrome87 chrome;
        public Safari87 safari;
        public Opera87 opera;
        public IosSaf87 ios_saf;
        public OpMini87 op_mini;
        public Android87 android;
        public Bb87 bb;
        public OpMob87 op_mob;
        public AndChr87 and_chr;
        public AndFf87 and_ff;
        public IeMob87 ie_mob;
        public AndUc87 and_uc;

#pragma warning restore 0649

    }

}
