// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats44
    {
#pragma warning disable 0649

        public Ie45 ie;
        public Edge45 edge;
        public Firefox45 firefox;
        public Chrome45 chrome;
        public Safari45 safari;
        public Opera45 opera;
        public IosSaf45 ios_saf;
        public OpMini45 op_mini;
        public Android45 android;
        public Bb45 bb;
        public OpMob45 op_mob;
        public AndChr45 and_chr;
        public AndFf45 and_ff;
        public IeMob45 ie_mob;
        public AndUc45 and_uc;

#pragma warning restore 0649

    }

}
