// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats11
    {
#pragma warning disable 0649

        public Ie12 ie;
        public Edge12 edge;
        public Firefox12 firefox;
        public Chrome12 chrome;
        public Safari12 safari;
        public Opera12 opera;
        public IosSaf12 ios_saf;
        public OpMini12 op_mini;
        public Android12 android;
        public Bb12 bb;
        public OpMob12 op_mob;
        public AndChr12 and_chr;
        public AndFf12 and_ff;
        public IeMob12 ie_mob;
        public AndUc12 and_uc;

#pragma warning restore 0649

    }

}
