// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats93
    {
#pragma warning disable 0649

        public Ie94 ie;
        public Edge94 edge;
        public Firefox94 firefox;
        public Chrome94 chrome;
        public Safari94 safari;
        public Opera94 opera;
        public IosSaf94 ios_saf;
        public OpMini94 op_mini;
        public Android94 android;
        public Bb94 bb;
        public OpMob94 op_mob;
        public AndChr94 and_chr;
        public AndFf94 and_ff;
        public IeMob94 ie_mob;
        public AndUc94 and_uc;

#pragma warning restore 0649

    }

}
