// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats102
    {
#pragma warning disable 0649

        public Ie103 ie;
        public Edge103 edge;
        public Firefox103 firefox;
        public Chrome103 chrome;
        public Safari103 safari;
        public Opera103 opera;
        public IosSaf103 ios_saf;
        public OpMini103 op_mini;
        public Android103 android;
        public Bb103 bb;
        public OpMob103 op_mob;
        public AndChr103 and_chr;
        public AndFf103 and_ff;
        public IeMob103 ie_mob;
        public AndUc103 and_uc;

#pragma warning restore 0649

    }

}
