// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats257
    {
#pragma warning disable 0649

        public Ie258 ie;
        public Edge258 edge;
        public Firefox258 firefox;
        public Chrome258 chrome;
        public Safari258 safari;
        public Opera258 opera;
        public IosSaf258 ios_saf;
        public OpMini258 op_mini;
        public Android258 android;
        public Bb258 bb;
        public OpMob258 op_mob;
        public AndChr258 and_chr;
        public AndFf258 and_ff;
        public IeMob258 ie_mob;
        public AndUc258 and_uc;

#pragma warning restore 0649

    }

}
