// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats106
    {
#pragma warning disable 0649

        public Ie107 ie;
        public Edge107 edge;
        public Firefox107 firefox;
        public Chrome107 chrome;
        public Safari107 safari;
        public Opera107 opera;
        public IosSaf107 ios_saf;
        public OpMini107 op_mini;
        public Android107 android;
        public Bb107 bb;
        public OpMob107 op_mob;
        public AndChr107 and_chr;
        public AndFf107 and_ff;
        public IeMob107 ie_mob;
        public AndUc107 and_uc;

#pragma warning restore 0649

    }

}
