// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats230
    {
#pragma warning disable 0649

        public Ie231 ie;
        public Edge231 edge;
        public Firefox231 firefox;
        public Chrome231 chrome;
        public Safari231 safari;
        public Opera231 opera;
        public IosSaf231 ios_saf;
        public OpMini231 op_mini;
        public Android231 android;
        public Bb231 bb;
        public OpMob231 op_mob;
        public AndChr231 and_chr;
        public AndFf231 and_ff;
        public IeMob231 ie_mob;
        public AndUc231 and_uc;

#pragma warning restore 0649

    }

}
