// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats269
    {
#pragma warning disable 0649

        public Ie270 ie;
        public Edge270 edge;
        public Firefox270 firefox;
        public Chrome270 chrome;
        public Safari270 safari;
        public Opera270 opera;
        public IosSaf270 ios_saf;
        public OpMini270 op_mini;
        public Android270 android;
        public Bb270 bb;
        public OpMob270 op_mob;
        public AndChr270 and_chr;
        public AndFf270 and_ff;
        public IeMob270 ie_mob;
        public AndUc270 and_uc;

#pragma warning restore 0649

    }

}
