// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats38
    {
#pragma warning disable 0649

        public Ie39 ie;
        public Edge39 edge;
        public Firefox39 firefox;
        public Chrome39 chrome;
        public Safari39 safari;
        public Opera39 opera;
        public IosSaf39 ios_saf;
        public OpMini39 op_mini;
        public Android39 android;
        public Bb39 bb;
        public OpMob39 op_mob;
        public AndChr39 and_chr;
        public AndFf39 and_ff;
        public IeMob39 ie_mob;
        public AndUc39 and_uc;

#pragma warning restore 0649

    }

}
