// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats77
    {
#pragma warning disable 0649

        public Ie78 ie;
        public Edge78 edge;
        public Firefox78 firefox;
        public Chrome78 chrome;
        public Safari78 safari;
        public Opera78 opera;
        public IosSaf78 ios_saf;
        public OpMini78 op_mini;
        public Android78 android;
        public Bb78 bb;
        public OpMob78 op_mob;
        public AndChr78 and_chr;
        public AndFf78 and_ff;
        public IeMob78 ie_mob;
        public AndUc78 and_uc;

#pragma warning restore 0649

    }

}
