// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats67
    {
#pragma warning disable 0649

        public Ie68 ie;
        public Edge68 edge;
        public Firefox68 firefox;
        public Chrome68 chrome;
        public Safari68 safari;
        public Opera68 opera;
        public IosSaf68 ios_saf;
        public OpMini68 op_mini;
        public Android68 android;
        public Bb68 bb;
        public OpMob68 op_mob;
        public AndChr68 and_chr;
        public AndFf68 and_ff;
        public IeMob68 ie_mob;
        public AndUc68 and_uc;

#pragma warning restore 0649

    }

}
