// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats174
    {
#pragma warning disable 0649

        public Ie175 ie;
        public Edge175 edge;
        public Firefox175 firefox;
        public Chrome175 chrome;
        public Safari175 safari;
        public Opera175 opera;
        public IosSaf175 ios_saf;
        public OpMini175 op_mini;
        public Android175 android;
        public Bb175 bb;
        public OpMob175 op_mob;
        public AndChr175 and_chr;
        public AndFf175 and_ff;
        public IeMob175 ie_mob;
        public AndUc175 and_uc;

#pragma warning restore 0649

    }

}
