// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats29
    {
#pragma warning disable 0649

        public Ie30 ie;
        public Edge30 edge;
        public Firefox30 firefox;
        public Chrome30 chrome;
        public Safari30 safari;
        public Opera30 opera;
        public IosSaf30 ios_saf;
        public OpMini30 op_mini;
        public Android30 android;
        public Bb30 bb;
        public OpMob30 op_mob;
        public AndChr30 and_chr;
        public AndFf30 and_ff;
        public IeMob30 ie_mob;
        public AndUc30 and_uc;

#pragma warning restore 0649

    }

}
