// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats133
    {
#pragma warning disable 0649

        public Ie134 ie;
        public Edge134 edge;
        public Firefox134 firefox;
        public Chrome134 chrome;
        public Safari134 safari;
        public Opera134 opera;
        public IosSaf134 ios_saf;
        public OpMini134 op_mini;
        public Android134 android;
        public Bb134 bb;
        public OpMob134 op_mob;
        public AndChr134 and_chr;
        public AndFf134 and_ff;
        public IeMob134 ie_mob;
        public AndUc134 and_uc;

#pragma warning restore 0649

    }

}
