// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats238
    {
#pragma warning disable 0649

        public Ie239 ie;
        public Edge239 edge;
        public Firefox239 firefox;
        public Chrome239 chrome;
        public Safari239 safari;
        public Opera239 opera;
        public IosSaf239 ios_saf;
        public OpMini239 op_mini;
        public Android239 android;
        public Bb239 bb;
        public OpMob239 op_mob;
        public AndChr239 and_chr;
        public AndFf239 and_ff;
        public IeMob239 ie_mob;
        public AndUc239 and_uc;

#pragma warning restore 0649

    }

}
