// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats138
    {
#pragma warning disable 0649

        public Ie139 ie;
        public Edge139 edge;
        public Firefox139 firefox;
        public Chrome139 chrome;
        public Safari139 safari;
        public Opera139 opera;
        public IosSaf139 ios_saf;
        public OpMini139 op_mini;
        public Android139 android;
        public Bb139 bb;
        public OpMob139 op_mob;
        public AndChr139 and_chr;
        public AndFf139 and_ff;
        public IeMob139 ie_mob;
        public AndUc139 and_uc;

#pragma warning restore 0649

    }

}
