// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats240
    {
#pragma warning disable 0649

        public Ie241 ie;
        public Edge241 edge;
        public Firefox241 firefox;
        public Chrome241 chrome;
        public Safari241 safari;
        public Opera241 opera;
        public IosSaf241 ios_saf;
        public OpMini241 op_mini;
        public Android241 android;
        public Bb241 bb;
        public OpMob241 op_mob;
        public AndChr241 and_chr;
        public AndFf241 and_ff;
        public IeMob241 ie_mob;
        public AndUc241 and_uc;

#pragma warning restore 0649

    }

}
