// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats158
    {
#pragma warning disable 0649

        public Ie159 ie;
        public Edge159 edge;
        public Firefox159 firefox;
        public Chrome159 chrome;
        public Safari159 safari;
        public Opera159 opera;
        public IosSaf159 ios_saf;
        public OpMini159 op_mini;
        public Android159 android;
        public Bb159 bb;
        public OpMob159 op_mob;
        public AndChr159 and_chr;
        public AndFf159 and_ff;
        public IeMob159 ie_mob;
        public AndUc159 and_uc;

#pragma warning restore 0649

    }

}
