// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats100
    {
#pragma warning disable 0649

        public Ie101 ie;
        public Edge101 edge;
        public Firefox101 firefox;
        public Chrome101 chrome;
        public Safari101 safari;
        public Opera101 opera;
        public IosSaf101 ios_saf;
        public OpMini101 op_mini;
        public Android101 android;
        public Bb101 bb;
        public OpMob101 op_mob;
        public AndChr101 and_chr;
        public AndFf101 and_ff;
        public IeMob101 ie_mob;
        public AndUc101 and_uc;

#pragma warning restore 0649

    }

}
