// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats58
    {
#pragma warning disable 0649

        public Ie59 ie;
        public Edge59 edge;
        public Firefox59 firefox;
        public Chrome59 chrome;
        public Safari59 safari;
        public Opera59 opera;
        public IosSaf59 ios_saf;
        public OpMini59 op_mini;
        public Android59 android;
        public Bb59 bb;
        public OpMob59 op_mob;
        public AndChr59 and_chr;
        public AndFf59 and_ff;
        public IeMob59 ie_mob;
        public AndUc59 and_uc;

#pragma warning restore 0649

    }

}
