// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats19
    {
#pragma warning disable 0649

        public Ie20 ie;
        public Edge20 edge;
        public Firefox20 firefox;
        public Chrome20 chrome;
        public Safari20 safari;
        public Opera20 opera;
        public IosSaf20 ios_saf;
        public OpMini20 op_mini;
        public Android20 android;
        public Bb20 bb;
        public OpMob20 op_mob;
        public AndChr20 and_chr;
        public AndFf20 and_ff;
        public IeMob20 ie_mob;
        public AndUc20 and_uc;

#pragma warning restore 0649

    }

}
