// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats166
    {
#pragma warning disable 0649

        public Ie167 ie;
        public Edge167 edge;
        public Firefox167 firefox;
        public Chrome167 chrome;
        public Safari167 safari;
        public Opera167 opera;
        public IosSaf167 ios_saf;
        public OpMini167 op_mini;
        public Android167 android;
        public Bb167 bb;
        public OpMob167 op_mob;
        public AndChr167 and_chr;
        public AndFf167 and_ff;
        public IeMob167 ie_mob;
        public AndUc167 and_uc;

#pragma warning restore 0649

    }

}
