// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats271
    {
#pragma warning disable 0649

        public Ie272 ie;
        public Edge272 edge;
        public Firefox272 firefox;
        public Chrome272 chrome;
        public Safari272 safari;
        public Opera272 opera;
        public IosSaf272 ios_saf;
        public OpMini272 op_mini;
        public Android272 android;
        public Bb272 bb;
        public OpMob272 op_mob;
        public AndChr272 and_chr;
        public AndFf272 and_ff;
        public IeMob272 ie_mob;
        public AndUc272 and_uc;

#pragma warning restore 0649

    }

}
