// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats233
    {
#pragma warning disable 0649

        public Ie234 ie;
        public Edge234 edge;
        public Firefox234 firefox;
        public Chrome234 chrome;
        public Safari234 safari;
        public Opera234 opera;
        public IosSaf234 ios_saf;
        public OpMini234 op_mini;
        public Android234 android;
        public Bb234 bb;
        public OpMob234 op_mob;
        public AndChr234 and_chr;
        public AndFf234 and_ff;
        public IeMob234 ie_mob;
        public AndUc234 and_uc;

#pragma warning restore 0649

    }

}
