// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats18
    {
#pragma warning disable 0649

        public Ie19 ie;
        public Edge19 edge;
        public Firefox19 firefox;
        public Chrome19 chrome;
        public Safari19 safari;
        public Opera19 opera;
        public IosSaf19 ios_saf;
        public OpMini19 op_mini;
        public Android19 android;
        public Bb19 bb;
        public OpMob19 op_mob;
        public AndChr19 and_chr;
        public AndFf19 and_ff;
        public IeMob19 ie_mob;
        public AndUc19 and_uc;

#pragma warning restore 0649

    }

}
