// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats281
    {
#pragma warning disable 0649

        public Ie282 ie;
        public Edge282 edge;
        public Firefox282 firefox;
        public Chrome282 chrome;
        public Safari282 safari;
        public Opera282 opera;
        public IosSaf282 ios_saf;
        public OpMini282 op_mini;
        public Android282 android;
        public Bb282 bb;
        public OpMob282 op_mob;
        public AndChr282 and_chr;
        public AndFf282 and_ff;
        public IeMob282 ie_mob;
        public AndUc282 and_uc;

#pragma warning restore 0649

    }

}
