// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats26
    {
#pragma warning disable 0649

        public Ie27 ie;
        public Edge27 edge;
        public Firefox27 firefox;
        public Chrome27 chrome;
        public Safari27 safari;
        public Opera27 opera;
        public IosSaf27 ios_saf;
        public OpMini27 op_mini;
        public Android27 android;
        public Bb27 bb;
        public OpMob27 op_mob;
        public AndChr27 and_chr;
        public AndFf27 and_ff;
        public IeMob27 ie_mob;
        public AndUc27 and_uc;

#pragma warning restore 0649

    }

}
