// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats3
    {
#pragma warning disable 0649

        public Ie4 ie;
        public Edge4 edge;
        public Firefox4 firefox;
        public Chrome4 chrome;
        public Safari4 safari;
        public Opera4 opera;
        public IosSaf4 ios_saf;
        public OpMini4 op_mini;
        public Android4 android;
        public Bb4 bb;
        public OpMob4 op_mob;
        public AndChr4 and_chr;
        public AndFf4 and_ff;
        public IeMob4 ie_mob;
        public AndUc4 and_uc;

#pragma warning restore 0649

    }

}
