// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats159
    {
#pragma warning disable 0649

        public Ie160 ie;
        public Edge160 edge;
        public Firefox160 firefox;
        public Chrome160 chrome;
        public Safari160 safari;
        public Opera160 opera;
        public IosSaf160 ios_saf;
        public OpMini160 op_mini;
        public Android160 android;
        public Bb160 bb;
        public OpMob160 op_mob;
        public AndChr160 and_chr;
        public AndFf160 and_ff;
        public IeMob160 ie_mob;
        public AndUc160 and_uc;

#pragma warning restore 0649

    }

}
