// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats182
    {
#pragma warning disable 0649

        public Ie183 ie;
        public Edge183 edge;
        public Firefox183 firefox;
        public Chrome183 chrome;
        public Safari183 safari;
        public Opera183 opera;
        public IosSaf183 ios_saf;
        public OpMini183 op_mini;
        public Android183 android;
        public Bb183 bb;
        public OpMob183 op_mob;
        public AndChr183 and_chr;
        public AndFf183 and_ff;
        public IeMob183 ie_mob;
        public AndUc183 and_uc;

#pragma warning restore 0649

    }

}
