// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Statuses
    {
#pragma warning disable 0649

        public string rec;
        public string pr;
        public string cr;
        public string wd;
        public string ls;
        public string other;
        public string unoff;

#pragma warning restore 0649

    }

}
