// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats37
    {
#pragma warning disable 0649

        public Ie38 ie;
        public Edge38 edge;
        public Firefox38 firefox;
        public Chrome38 chrome;
        public Safari38 safari;
        public Opera38 opera;
        public IosSaf38 ios_saf;
        public OpMini38 op_mini;
        public Android38 android;
        public Bb38 bb;
        public OpMob38 op_mob;
        public AndChr38 and_chr;
        public AndFf38 and_ff;
        public IeMob38 ie_mob;
        public AndUc38 and_uc;

#pragma warning restore 0649

    }

}
