// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats
    {
#pragma warning disable 0649

        public Ie2 ie;
        public Edge2 edge;
        public Firefox2 firefox;
        public Chrome2 chrome;
        public Safari2 safari;
        public Opera2 opera;
        public IosSaf2 ios_saf;
        public OpMini2 op_mini;
        public Android2 android;
        public Bb2 bb;
        public OpMob2 op_mob;
        public AndChr2 and_chr;
        public AndFf2 and_ff;
        public IeMob2 ie_mob;
        public AndUc2 and_uc;

#pragma warning restore 0649

    }

}
