// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats112
    {
#pragma warning disable 0649

        public Ie113 ie;
        public Edge113 edge;
        public Firefox113 firefox;
        public Chrome113 chrome;
        public Safari113 safari;
        public Opera113 opera;
        public IosSaf113 ios_saf;
        public OpMini113 op_mini;
        public Android113 android;
        public Bb113 bb;
        public OpMob113 op_mob;
        public AndChr113 and_chr;
        public AndFf113 and_ff;
        public IeMob113 ie_mob;
        public AndUc113 and_uc;

#pragma warning restore 0649

    }

}
