// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats184
    {
#pragma warning disable 0649

        public Ie185 ie;
        public Edge185 edge;
        public Firefox185 firefox;
        public Chrome185 chrome;
        public Safari185 safari;
        public Opera185 opera;
        public IosSaf185 ios_saf;
        public OpMini185 op_mini;
        public Android185 android;
        public Bb185 bb;
        public OpMob185 op_mob;
        public AndChr185 and_chr;
        public AndFf185 and_ff;
        public IeMob185 ie_mob;
        public AndUc185 and_uc;

#pragma warning restore 0649

    }

}
