// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats39
    {
#pragma warning disable 0649

        public Ie40 ie;
        public Edge40 edge;
        public Firefox40 firefox;
        public Chrome40 chrome;
        public Safari40 safari;
        public Opera40 opera;
        public IosSaf40 ios_saf;
        public OpMini40 op_mini;
        public Android40 android;
        public Bb40 bb;
        public OpMob40 op_mob;
        public AndChr40 and_chr;
        public AndFf40 and_ff;
        public IeMob40 ie_mob;
        public AndUc40 and_uc;

#pragma warning restore 0649

    }

}
