// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats52
    {
#pragma warning disable 0649

        public Ie53 ie;
        public Edge53 edge;
        public Firefox53 firefox;
        public Chrome53 chrome;
        public Safari53 safari;
        public Opera53 opera;
        public IosSaf53 ios_saf;
        public OpMini53 op_mini;
        public Android53 android;
        public Bb53 bb;
        public OpMob53 op_mob;
        public AndChr53 and_chr;
        public AndFf53 and_ff;
        public IeMob53 ie_mob;
        public AndUc53 and_uc;

#pragma warning restore 0649

    }

}
