// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats110
    {
#pragma warning disable 0649

        public Ie111 ie;
        public Edge111 edge;
        public Firefox111 firefox;
        public Chrome111 chrome;
        public Safari111 safari;
        public Opera111 opera;
        public IosSaf111 ios_saf;
        public OpMini111 op_mini;
        public Android111 android;
        public Bb111 bb;
        public OpMob111 op_mob;
        public AndChr111 and_chr;
        public AndFf111 and_ff;
        public IeMob111 ie_mob;
        public AndUc111 and_uc;

#pragma warning restore 0649

    }

}
