// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats153
    {
#pragma warning disable 0649

        public Ie154 ie;
        public Edge154 edge;
        public Firefox154 firefox;
        public Chrome154 chrome;
        public Safari154 safari;
        public Opera154 opera;
        public IosSaf154 ios_saf;
        public OpMini154 op_mini;
        public Android154 android;
        public Bb154 bb;
        public OpMob154 op_mob;
        public AndChr154 and_chr;
        public AndFf154 and_ff;
        public IeMob154 ie_mob;
        public AndUc154 and_uc;

#pragma warning restore 0649

    }

}
