// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats49
    {
#pragma warning disable 0649

        public Ie50 ie;
        public Edge50 edge;
        public Firefox50 firefox;
        public Chrome50 chrome;
        public Safari50 safari;
        public Opera50 opera;
        public IosSaf50 ios_saf;
        public OpMini50 op_mini;
        public Android50 android;
        public Bb50 bb;
        public OpMob50 op_mob;
        public AndChr50 and_chr;
        public AndFf50 and_ff;
        public IeMob50 ie_mob;
        public AndUc50 and_uc;

#pragma warning restore 0649

    }

}
