// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats290
    {
#pragma warning disable 0649

        public Ie291 ie;
        public Edge291 edge;
        public Firefox291 firefox;
        public Chrome291 chrome;
        public Safari291 safari;
        public Opera291 opera;
        public IosSaf291 ios_saf;
        public OpMini291 op_mini;
        public Android291 android;
        public Bb291 bb;
        public OpMob291 op_mob;
        public AndChr291 and_chr;
        public AndFf291 and_ff;
        public IeMob291 ie_mob;
        public AndUc291 and_uc;

#pragma warning restore 0649

    }

}
