// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats127
    {
#pragma warning disable 0649

        public Ie128 ie;
        public Edge128 edge;
        public Firefox128 firefox;
        public Chrome128 chrome;
        public Safari128 safari;
        public Opera128 opera;
        public IosSaf128 ios_saf;
        public OpMini128 op_mini;
        public Android128 android;
        public Bb128 bb;
        public OpMob128 op_mob;
        public AndChr128 and_chr;
        public AndFf128 and_ff;
        public IeMob128 ie_mob;
        public AndUc128 and_uc;

#pragma warning restore 0649

    }

}
