// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats220
    {
#pragma warning disable 0649

        public Ie221 ie;
        public Edge221 edge;
        public Firefox221 firefox;
        public Chrome221 chrome;
        public Safari221 safari;
        public Opera221 opera;
        public IosSaf221 ios_saf;
        public OpMini221 op_mini;
        public Android221 android;
        public Bb221 bb;
        public OpMob221 op_mob;
        public AndChr221 and_chr;
        public AndFf221 and_ff;
        public IeMob221 ie_mob;
        public AndUc221 and_uc;

#pragma warning restore 0649

    }

}
