// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats76
    {
#pragma warning disable 0649

        public Ie77 ie;
        public Edge77 edge;
        public Firefox77 firefox;
        public Chrome77 chrome;
        public Safari77 safari;
        public Opera77 opera;
        public IosSaf77 ios_saf;
        public OpMini77 op_mini;
        public Android77 android;
        public Bb77 bb;
        public OpMob77 op_mob;
        public AndChr77 and_chr;
        public AndFf77 and_ff;
        public IeMob77 ie_mob;
        public AndUc77 and_uc;

#pragma warning restore 0649

    }

}
