// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats80
    {
#pragma warning disable 0649

        public Ie81 ie;
        public Edge81 edge;
        public Firefox81 firefox;
        public Chrome81 chrome;
        public Safari81 safari;
        public Opera81 opera;
        public IosSaf81 ios_saf;
        public OpMini81 op_mini;
        public Android81 android;
        public Bb81 bb;
        public OpMob81 op_mob;
        public AndChr81 and_chr;
        public AndFf81 and_ff;
        public IeMob81 ie_mob;
        public AndUc81 and_uc;

#pragma warning restore 0649

    }

}
