// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats66
    {
#pragma warning disable 0649

        public Ie67 ie;
        public Edge67 edge;
        public Firefox67 firefox;
        public Chrome67 chrome;
        public Safari67 safari;
        public Opera67 opera;
        public IosSaf67 ios_saf;
        public OpMini67 op_mini;
        public Android67 android;
        public Bb67 bb;
        public OpMob67 op_mob;
        public AndChr67 and_chr;
        public AndFf67 and_ff;
        public IeMob67 ie_mob;
        public AndUc67 and_uc;

#pragma warning restore 0649

    }

}
