// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats180
    {
#pragma warning disable 0649

        public Ie181 ie;
        public Edge181 edge;
        public Firefox181 firefox;
        public Chrome181 chrome;
        public Safari181 safari;
        public Opera181 opera;
        public IosSaf181 ios_saf;
        public OpMini181 op_mini;
        public Android181 android;
        public Bb181 bb;
        public OpMob181 op_mob;
        public AndChr181 and_chr;
        public AndFf181 and_ff;
        public IeMob181 ie_mob;
        public AndUc181 and_uc;

#pragma warning restore 0649

    }

}
