// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats75
    {
#pragma warning disable 0649

        public Ie76 ie;
        public Edge76 edge;
        public Firefox76 firefox;
        public Chrome76 chrome;
        public Safari76 safari;
        public Opera76 opera;
        public IosSaf76 ios_saf;
        public OpMini76 op_mini;
        public Android76 android;
        public Bb76 bb;
        public OpMob76 op_mob;
        public AndChr76 and_chr;
        public AndFf76 and_ff;
        public IeMob76 ie_mob;
        public AndUc76 and_uc;

#pragma warning restore 0649

    }

}
