// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats42
    {
#pragma warning disable 0649

        public Ie43 ie;
        public Edge43 edge;
        public Firefox43 firefox;
        public Chrome43 chrome;
        public Safari43 safari;
        public Opera43 opera;
        public IosSaf43 ios_saf;
        public OpMini43 op_mini;
        public Android43 android;
        public Bb43 bb;
        public OpMob43 op_mob;
        public AndChr43 and_chr;
        public AndFf43 and_ff;
        public IeMob43 ie_mob;
        public AndUc43 and_uc;

#pragma warning restore 0649

    }

}
