// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats96
    {
#pragma warning disable 0649

        public Ie97 ie;
        public Edge97 edge;
        public Firefox97 firefox;
        public Chrome97 chrome;
        public Safari97 safari;
        public Opera97 opera;
        public IosSaf97 ios_saf;
        public OpMini97 op_mini;
        public Android97 android;
        public Bb97 bb;
        public OpMob97 op_mob;
        public AndChr97 and_chr;
        public AndFf97 and_ff;
        public IeMob97 ie_mob;
        public AndUc97 and_uc;

#pragma warning restore 0649

    }

}
