// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats150
    {
#pragma warning disable 0649

        public Ie151 ie;
        public Edge151 edge;
        public Firefox151 firefox;
        public Chrome151 chrome;
        public Safari151 safari;
        public Opera151 opera;
        public IosSaf151 ios_saf;
        public OpMini151 op_mini;
        public Android151 android;
        public Bb151 bb;
        public OpMob151 op_mob;
        public AndChr151 and_chr;
        public AndFf151 and_ff;
        public IeMob151 ie_mob;
        public AndUc151 and_uc;

#pragma warning restore 0649

    }

}
