// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats251
    {
#pragma warning disable 0649

        public Ie252 ie;
        public Edge252 edge;
        public Firefox252 firefox;
        public Chrome252 chrome;
        public Safari252 safari;
        public Opera252 opera;
        public IosSaf252 ios_saf;
        public OpMini252 op_mini;
        public Android252 android;
        public Bb252 bb;
        public OpMob252 op_mob;
        public AndChr252 and_chr;
        public AndFf252 and_ff;
        public IeMob252 ie_mob;
        public AndUc252 and_uc;

#pragma warning restore 0649

    }

}
