// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats118
    {
#pragma warning disable 0649

        public Ie119 ie;
        public Edge119 edge;
        public Firefox119 firefox;
        public Chrome119 chrome;
        public Safari119 safari;
        public Opera119 opera;
        public IosSaf119 ios_saf;
        public OpMini119 op_mini;
        public Android119 android;
        public Bb119 bb;
        public OpMob119 op_mob;
        public AndChr119 and_chr;
        public AndFf119 and_ff;
        public IeMob119 ie_mob;
        public AndUc119 and_uc;

#pragma warning restore 0649

    }

}
