// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats212
    {
#pragma warning disable 0649

        public Ie213 ie;
        public Edge213 edge;
        public Firefox213 firefox;
        public Chrome213 chrome;
        public Safari213 safari;
        public Opera213 opera;
        public IosSaf213 ios_saf;
        public OpMini213 op_mini;
        public Android213 android;
        public Bb213 bb;
        public OpMob213 op_mob;
        public AndChr213 and_chr;
        public AndFf213 and_ff;
        public IeMob213 ie_mob;
        public AndUc213 and_uc;

#pragma warning restore 0649

    }

}
