// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats78
    {
#pragma warning disable 0649

        public Ie79 ie;
        public Edge79 edge;
        public Firefox79 firefox;
        public Chrome79 chrome;
        public Safari79 safari;
        public Opera79 opera;
        public IosSaf79 ios_saf;
        public OpMini79 op_mini;
        public Android79 android;
        public Bb79 bb;
        public OpMob79 op_mob;
        public AndChr79 and_chr;
        public AndFf79 and_ff;
        public IeMob79 ie_mob;
        public AndUc79 and_uc;

#pragma warning restore 0649

    }

}
