// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats229
    {
#pragma warning disable 0649

        public Ie230 ie;
        public Edge230 edge;
        public Firefox230 firefox;
        public Chrome230 chrome;
        public Safari230 safari;
        public Opera230 opera;
        public IosSaf230 ios_saf;
        public OpMini230 op_mini;
        public Android230 android;
        public Bb230 bb;
        public OpMob230 op_mob;
        public AndChr230 and_chr;
        public AndFf230 and_ff;
        public IeMob230 ie_mob;
        public AndUc230 and_uc;

#pragma warning restore 0649

    }

}
