// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats213
    {
#pragma warning disable 0649

        public Ie214 ie;
        public Edge214 edge;
        public Firefox214 firefox;
        public Chrome214 chrome;
        public Safari214 safari;
        public Opera214 opera;
        public IosSaf214 ios_saf;
        public OpMini214 op_mini;
        public Android214 android;
        public Bb214 bb;
        public OpMob214 op_mob;
        public AndChr214 and_chr;
        public AndFf214 and_ff;
        public IeMob214 ie_mob;
        public AndUc214 and_uc;

#pragma warning restore 0649

    }

}
