// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats172
    {
#pragma warning disable 0649

        public Ie173 ie;
        public Edge173 edge;
        public Firefox173 firefox;
        public Chrome173 chrome;
        public Safari173 safari;
        public Opera173 opera;
        public IosSaf173 ios_saf;
        public OpMini173 op_mini;
        public Android173 android;
        public Bb173 bb;
        public OpMob173 op_mob;
        public AndChr173 and_chr;
        public AndFf173 and_ff;
        public IeMob173 ie_mob;
        public AndUc173 and_uc;

#pragma warning restore 0649

    }

}
