// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats23
    {
#pragma warning disable 0649

        public Ie24 ie;
        public Edge24 edge;
        public Firefox24 firefox;
        public Chrome24 chrome;
        public Safari24 safari;
        public Opera24 opera;
        public IosSaf24 ios_saf;
        public OpMini24 op_mini;
        public Android24 android;
        public Bb24 bb;
        public OpMob24 op_mob;
        public AndChr24 and_chr;
        public AndFf24 and_ff;
        public IeMob24 ie_mob;
        public AndUc24 and_uc;

#pragma warning restore 0649

    }

}
