// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats261
    {
#pragma warning disable 0649

        public Ie262 ie;
        public Edge262 edge;
        public Firefox262 firefox;
        public Chrome262 chrome;
        public Safari262 safari;
        public Opera262 opera;
        public IosSaf262 ios_saf;
        public OpMini262 op_mini;
        public Android262 android;
        public Bb262 bb;
        public OpMob262 op_mob;
        public AndChr262 and_chr;
        public AndFf262 and_ff;
        public IeMob262 ie_mob;
        public AndUc262 and_uc;

#pragma warning restore 0649

    }

}
