// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats234
    {
#pragma warning disable 0649

        public Ie235 ie;
        public Edge235 edge;
        public Firefox235 firefox;
        public Chrome235 chrome;
        public Safari235 safari;
        public Opera235 opera;
        public IosSaf235 ios_saf;
        public OpMini235 op_mini;
        public Android235 android;
        public Bb235 bb;
        public OpMob235 op_mob;
        public AndChr235 and_chr;
        public AndFf235 and_ff;
        public IeMob235 ie_mob;
        public AndUc235 and_uc;

#pragma warning restore 0649

    }

}
