// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats103
    {
#pragma warning disable 0649

        public Ie104 ie;
        public Edge104 edge;
        public Firefox104 firefox;
        public Chrome104 chrome;
        public Safari104 safari;
        public Opera104 opera;
        public IosSaf104 ios_saf;
        public OpMini104 op_mini;
        public Android104 android;
        public Bb104 bb;
        public OpMob104 op_mob;
        public AndChr104 and_chr;
        public AndFf104 and_ff;
        public IeMob104 ie_mob;
        public AndUc104 and_uc;

#pragma warning restore 0649

    }

}
