// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats137
    {
#pragma warning disable 0649

        public Ie138 ie;
        public Edge138 edge;
        public Firefox138 firefox;
        public Chrome138 chrome;
        public Safari138 safari;
        public Opera138 opera;
        public IosSaf138 ios_saf;
        public OpMini138 op_mini;
        public Android138 android;
        public Bb138 bb;
        public OpMob138 op_mob;
        public AndChr138 and_chr;
        public AndFf138 and_ff;
        public IeMob138 ie_mob;
        public AndUc138 and_uc;

#pragma warning restore 0649

    }

}
