// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats228
    {
#pragma warning disable 0649

        public Ie229 ie;
        public Edge229 edge;
        public Firefox229 firefox;
        public Chrome229 chrome;
        public Safari229 safari;
        public Opera229 opera;
        public IosSaf229 ios_saf;
        public OpMini229 op_mini;
        public Android229 android;
        public Bb229 bb;
        public OpMob229 op_mob;
        public AndChr229 and_chr;
        public AndFf229 and_ff;
        public IeMob229 ie_mob;
        public AndUc229 and_uc;

#pragma warning restore 0649

    }

}
