// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats91
    {
#pragma warning disable 0649

        public Ie92 ie;
        public Edge92 edge;
        public Firefox92 firefox;
        public Chrome92 chrome;
        public Safari92 safari;
        public Opera92 opera;
        public IosSaf92 ios_saf;
        public OpMini92 op_mini;
        public Android92 android;
        public Bb92 bb;
        public OpMob92 op_mob;
        public AndChr92 and_chr;
        public AndFf92 and_ff;
        public IeMob92 ie_mob;
        public AndUc92 and_uc;

#pragma warning restore 0649

    }

}
