// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats235
    {
#pragma warning disable 0649

        public Ie236 ie;
        public Edge236 edge;
        public Firefox236 firefox;
        public Chrome236 chrome;
        public Safari236 safari;
        public Opera236 opera;
        public IosSaf236 ios_saf;
        public OpMini236 op_mini;
        public Android236 android;
        public Bb236 bb;
        public OpMob236 op_mob;
        public AndChr236 and_chr;
        public AndFf236 and_ff;
        public IeMob236 ie_mob;
        public AndUc236 and_uc;

#pragma warning restore 0649

    }

}
