// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats51
    {
#pragma warning disable 0649

        public Ie52 ie;
        public Edge52 edge;
        public Firefox52 firefox;
        public Chrome52 chrome;
        public Safari52 safari;
        public Opera52 opera;
        public IosSaf52 ios_saf;
        public OpMini52 op_mini;
        public Android52 android;
        public Bb52 bb;
        public OpMob52 op_mob;
        public AndChr52 and_chr;
        public AndFf52 and_ff;
        public IeMob52 ie_mob;
        public AndUc52 and_uc;

#pragma warning restore 0649

    }

}
