// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats9
    {
#pragma warning disable 0649

        public Ie10 ie;
        public Edge10 edge;
        public Firefox10 firefox;
        public Chrome10 chrome;
        public Safari10 safari;
        public Opera10 opera;
        public IosSaf10 ios_saf;
        public OpMini10 op_mini;
        public Android10 android;
        public Bb10 bb;
        public OpMob10 op_mob;
        public AndChr10 and_chr;
        public AndFf10 and_ff;
        public IeMob10 ie_mob;
        public AndUc10 and_uc;

#pragma warning restore 0649

    }

}
