// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats224
    {
#pragma warning disable 0649

        public Ie225 ie;
        public Edge225 edge;
        public Firefox225 firefox;
        public Chrome225 chrome;
        public Safari225 safari;
        public Opera225 opera;
        public IosSaf225 ios_saf;
        public OpMini225 op_mini;
        public Android225 android;
        public Bb225 bb;
        public OpMob225 op_mob;
        public AndChr225 and_chr;
        public AndFf225 and_ff;
        public IeMob225 ie_mob;
        public AndUc225 and_uc;

#pragma warning restore 0649

    }

}
