// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats216
    {
#pragma warning disable 0649

        public Ie217 ie;
        public Edge217 edge;
        public Firefox217 firefox;
        public Chrome217 chrome;
        public Safari217 safari;
        public Opera217 opera;
        public IosSaf217 ios_saf;
        public OpMini217 op_mini;
        public Android217 android;
        public Bb217 bb;
        public OpMob217 op_mob;
        public AndChr217 and_chr;
        public AndFf217 and_ff;
        public IeMob217 ie_mob;
        public AndUc217 and_uc;

#pragma warning restore 0649

    }

}
