// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats85
    {
#pragma warning disable 0649

        public Ie86 ie;
        public Edge86 edge;
        public Firefox86 firefox;
        public Chrome86 chrome;
        public Safari86 safari;
        public Opera86 opera;
        public IosSaf86 ios_saf;
        public OpMini86 op_mini;
        public Android86 android;
        public Bb86 bb;
        public OpMob86 op_mob;
        public AndChr86 and_chr;
        public AndFf86 and_ff;
        public IeMob86 ie_mob;
        public AndUc86 and_uc;

#pragma warning restore 0649

    }

}
