// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats64
    {
#pragma warning disable 0649

        public Ie65 ie;
        public Edge65 edge;
        public Firefox65 firefox;
        public Chrome65 chrome;
        public Safari65 safari;
        public Opera65 opera;
        public IosSaf65 ios_saf;
        public OpMini65 op_mini;
        public Android65 android;
        public Bb65 bb;
        public OpMob65 op_mob;
        public AndChr65 and_chr;
        public AndFf65 and_ff;
        public IeMob65 ie_mob;
        public AndUc65 and_uc;

#pragma warning restore 0649

    }

}
