// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats123
    {
#pragma warning disable 0649

        public Ie124 ie;
        public Edge124 edge;
        public Firefox124 firefox;
        public Chrome124 chrome;
        public Safari124 safari;
        public Opera124 opera;
        public IosSaf124 ios_saf;
        public OpMini124 op_mini;
        public Android124 android;
        public Bb124 bb;
        public OpMob124 op_mob;
        public AndChr124 and_chr;
        public AndFf124 and_ff;
        public IeMob124 ie_mob;
        public AndUc124 and_uc;

#pragma warning restore 0649

    }

}
