// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats131
    {
#pragma warning disable 0649

        public Ie132 ie;
        public Edge132 edge;
        public Firefox132 firefox;
        public Chrome132 chrome;
        public Safari132 safari;
        public Opera132 opera;
        public IosSaf132 ios_saf;
        public OpMini132 op_mini;
        public Android132 android;
        public Bb132 bb;
        public OpMob132 op_mob;
        public AndChr132 and_chr;
        public AndFf132 and_ff;
        public IeMob132 ie_mob;
        public AndUc132 and_uc;

#pragma warning restore 0649

    }

}
