// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats214
    {
#pragma warning disable 0649

        public Ie215 ie;
        public Edge215 edge;
        public Firefox215 firefox;
        public Chrome215 chrome;
        public Safari215 safari;
        public Opera215 opera;
        public IosSaf215 ios_saf;
        public OpMini215 op_mini;
        public Android215 android;
        public Bb215 bb;
        public OpMob215 op_mob;
        public AndChr215 and_chr;
        public AndFf215 and_ff;
        public IeMob215 ie_mob;
        public AndUc215 and_uc;

#pragma warning restore 0649

    }

}
