// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats126
    {
#pragma warning disable 0649

        public Ie127 ie;
        public Edge127 edge;
        public Firefox127 firefox;
        public Chrome127 chrome;
        public Safari127 safari;
        public Opera127 opera;
        public IosSaf127 ios_saf;
        public OpMini127 op_mini;
        public Android127 android;
        public Bb127 bb;
        public OpMob127 op_mob;
        public AndChr127 and_chr;
        public AndFf127 and_ff;
        public IeMob127 ie_mob;
        public AndUc127 and_uc;

#pragma warning restore 0649

    }

}
