// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats183
    {
#pragma warning disable 0649

        public Ie184 ie;
        public Edge184 edge;
        public Firefox184 firefox;
        public Chrome184 chrome;
        public Safari184 safari;
        public Opera184 opera;
        public IosSaf184 ios_saf;
        public OpMini184 op_mini;
        public Android184 android;
        public Bb184 bb;
        public OpMob184 op_mob;
        public AndChr184 and_chr;
        public AndFf184 and_ff;
        public IeMob184 ie_mob;
        public AndUc184 and_uc;

#pragma warning restore 0649

    }

}
