// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats122
    {
#pragma warning disable 0649

        public Ie123 ie;
        public Edge123 edge;
        public Firefox123 firefox;
        public Chrome123 chrome;
        public Safari123 safari;
        public Opera123 opera;
        public IosSaf123 ios_saf;
        public OpMini123 op_mini;
        public Android123 android;
        public Bb123 bb;
        public OpMob123 op_mob;
        public AndChr123 and_chr;
        public AndFf123 and_ff;
        public IeMob123 ie_mob;
        public AndUc123 and_uc;

#pragma warning restore 0649

    }

}
