// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats120
    {
#pragma warning disable 0649

        public Ie121 ie;
        public Edge121 edge;
        public Firefox121 firefox;
        public Chrome121 chrome;
        public Safari121 safari;
        public Opera121 opera;
        public IosSaf121 ios_saf;
        public OpMini121 op_mini;
        public Android121 android;
        public Bb121 bb;
        public OpMob121 op_mob;
        public AndChr121 and_chr;
        public AndFf121 and_ff;
        public IeMob121 ie_mob;
        public AndUc121 and_uc;

#pragma warning restore 0649

    }

}
