// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats56
    {
#pragma warning disable 0649

        public Ie57 ie;
        public Edge57 edge;
        public Firefox57 firefox;
        public Chrome57 chrome;
        public Safari57 safari;
        public Opera57 opera;
        public IosSaf57 ios_saf;
        public OpMini57 op_mini;
        public Android57 android;
        public Bb57 bb;
        public OpMob57 op_mob;
        public AndChr57 and_chr;
        public AndFf57 and_ff;
        public IeMob57 ie_mob;
        public AndUc57 and_uc;

#pragma warning restore 0649

    }

}
