// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats27
    {
#pragma warning disable 0649

        public Ie28 ie;
        public Edge28 edge;
        public Firefox28 firefox;
        public Chrome28 chrome;
        public Safari28 safari;
        public Opera28 opera;
        public IosSaf28 ios_saf;
        public OpMini28 op_mini;
        public Android28 android;
        public Bb28 bb;
        public OpMob28 op_mob;
        public AndChr28 and_chr;
        public AndFf28 and_ff;
        public IeMob28 ie_mob;
        public AndUc28 and_uc;

#pragma warning restore 0649

    }

}
