// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats41
    {
#pragma warning disable 0649

        public Ie42 ie;
        public Edge42 edge;
        public Firefox42 firefox;
        public Chrome42 chrome;
        public Safari42 safari;
        public Opera42 opera;
        public IosSaf42 ios_saf;
        public OpMini42 op_mini;
        public Android42 android;
        public Bb42 bb;
        public OpMob42 op_mob;
        public AndChr42 and_chr;
        public AndFf42 and_ff;
        public IeMob42 ie_mob;
        public AndUc42 and_uc;

#pragma warning restore 0649

    }

}
