// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats206
    {
#pragma warning disable 0649

        public Ie207 ie;
        public Edge207 edge;
        public Firefox207 firefox;
        public Chrome207 chrome;
        public Safari207 safari;
        public Opera207 opera;
        public IosSaf207 ios_saf;
        public OpMini207 op_mini;
        public Android207 android;
        public Bb207 bb;
        public OpMob207 op_mob;
        public AndChr207 and_chr;
        public AndFf207 and_ff;
        public IeMob207 ie_mob;
        public AndUc207 and_uc;

#pragma warning restore 0649

    }

}
