// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats113
    {
#pragma warning disable 0649

        public Ie114 ie;
        public Edge114 edge;
        public Firefox114 firefox;
        public Chrome114 chrome;
        public Safari114 safari;
        public Opera114 opera;
        public IosSaf114 ios_saf;
        public OpMini114 op_mini;
        public Android114 android;
        public Bb114 bb;
        public OpMob114 op_mob;
        public AndChr114 and_chr;
        public AndFf114 and_ff;
        public IeMob114 ie_mob;
        public AndUc114 and_uc;

#pragma warning restore 0649

    }

}
