// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats32
    {
#pragma warning disable 0649

        public Ie33 ie;
        public Edge33 edge;
        public Firefox33 firefox;
        public Chrome33 chrome;
        public Safari33 safari;
        public Opera33 opera;
        public IosSaf33 ios_saf;
        public OpMini33 op_mini;
        public Android33 android;
        public Bb33 bb;
        public OpMob33 op_mob;
        public AndChr33 and_chr;
        public AndFf33 and_ff;
        public IeMob33 ie_mob;
        public AndUc33 and_uc;

#pragma warning restore 0649

    }

}
