// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats211
    {
#pragma warning disable 0649

        public Ie212 ie;
        public Edge212 edge;
        public Firefox212 firefox;
        public Chrome212 chrome;
        public Safari212 safari;
        public Opera212 opera;
        public IosSaf212 ios_saf;
        public OpMini212 op_mini;
        public Android212 android;
        public Bb212 bb;
        public OpMob212 op_mob;
        public AndChr212 and_chr;
        public AndFf212 and_ff;
        public IeMob212 ie_mob;
        public AndUc212 and_uc;

#pragma warning restore 0649

    }

}
