// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats283
    {
#pragma warning disable 0649

        public Ie284 ie;
        public Edge284 edge;
        public Firefox284 firefox;
        public Chrome284 chrome;
        public Safari284 safari;
        public Opera284 opera;
        public IosSaf284 ios_saf;
        public OpMini284 op_mini;
        public Android284 android;
        public Bb284 bb;
        public OpMob284 op_mob;
        public AndChr284 and_chr;
        public AndFf284 and_ff;
        public IeMob284 ie_mob;
        public AndUc284 and_uc;

#pragma warning restore 0649

    }

}
