// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats187
    {
#pragma warning disable 0649

        public Ie188 ie;
        public Edge188 edge;
        public Firefox188 firefox;
        public Chrome188 chrome;
        public Safari188 safari;
        public Opera188 opera;
        public IosSaf188 ios_saf;
        public OpMini188 op_mini;
        public Android188 android;
        public Bb188 bb;
        public OpMob188 op_mob;
        public AndChr188 and_chr;
        public AndFf188 and_ff;
        public IeMob188 ie_mob;
        public AndUc188 and_uc;

#pragma warning restore 0649

    }

}
