// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats143
    {
#pragma warning disable 0649

        public Ie144 ie;
        public Edge144 edge;
        public Firefox144 firefox;
        public Chrome144 chrome;
        public Safari144 safari;
        public Opera144 opera;
        public IosSaf144 ios_saf;
        public OpMini144 op_mini;
        public Android144 android;
        public Bb144 bb;
        public OpMob144 op_mob;
        public AndChr144 and_chr;
        public AndFf144 and_ff;
        public IeMob144 ie_mob;
        public AndUc144 and_uc;

#pragma warning restore 0649

    }

}
