// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats288
    {
#pragma warning disable 0649

        public Ie289 ie;
        public Edge289 edge;
        public Firefox289 firefox;
        public Chrome289 chrome;
        public Safari289 safari;
        public Opera289 opera;
        public IosSaf289 ios_saf;
        public OpMini289 op_mini;
        public Android289 android;
        public Bb289 bb;
        public OpMob289 op_mob;
        public AndChr289 and_chr;
        public AndFf289 and_ff;
        public IeMob289 ie_mob;
        public AndUc289 and_uc;

#pragma warning restore 0649

    }

}
