// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats168
    {
#pragma warning disable 0649

        public Ie169 ie;
        public Edge169 edge;
        public Firefox169 firefox;
        public Chrome169 chrome;
        public Safari169 safari;
        public Opera169 opera;
        public IosSaf169 ios_saf;
        public OpMini169 op_mini;
        public Android169 android;
        public Bb169 bb;
        public OpMob169 op_mob;
        public AndChr169 and_chr;
        public AndFf169 and_ff;
        public IeMob169 ie_mob;
        public AndUc169 and_uc;

#pragma warning restore 0649

    }

}
