// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats83
    {
#pragma warning disable 0649

        public Ie84 ie;
        public Edge84 edge;
        public Firefox84 firefox;
        public Chrome84 chrome;
        public Safari84 safari;
        public Opera84 opera;
        public IosSaf84 ios_saf;
        public OpMini84 op_mini;
        public Android84 android;
        public Bb84 bb;
        public OpMob84 op_mob;
        public AndChr84 and_chr;
        public AndFf84 and_ff;
        public IeMob84 ie_mob;
        public AndUc84 and_uc;

#pragma warning restore 0649

    }

}
