// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats193
    {
#pragma warning disable 0649

        public Ie194 ie;
        public Edge194 edge;
        public Firefox194 firefox;
        public Chrome194 chrome;
        public Safari194 safari;
        public Opera194 opera;
        public IosSaf194 ios_saf;
        public OpMini194 op_mini;
        public Android194 android;
        public Bb194 bb;
        public OpMob194 op_mob;
        public AndChr194 and_chr;
        public AndFf194 and_ff;
        public IeMob194 ie_mob;
        public AndUc194 and_uc;

#pragma warning restore 0649

    }

}
