// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats40
    {
#pragma warning disable 0649

        public Ie41 ie;
        public Edge41 edge;
        public Firefox41 firefox;
        public Chrome41 chrome;
        public Safari41 safari;
        public Opera41 opera;
        public IosSaf41 ios_saf;
        public OpMini41 op_mini;
        public Android41 android;
        public Bb41 bb;
        public OpMob41 op_mob;
        public AndChr41 and_chr;
        public AndFf41 and_ff;
        public IeMob41 ie_mob;
        public AndUc41 and_uc;

#pragma warning restore 0649

    }

}
