// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats132
    {
#pragma warning disable 0649

        public Ie133 ie;
        public Edge133 edge;
        public Firefox133 firefox;
        public Chrome133 chrome;
        public Safari133 safari;
        public Opera133 opera;
        public IosSaf133 ios_saf;
        public OpMini133 op_mini;
        public Android133 android;
        public Bb133 bb;
        public OpMob133 op_mob;
        public AndChr133 and_chr;
        public AndFf133 and_ff;
        public IeMob133 ie_mob;
        public AndUc133 and_uc;

#pragma warning restore 0649

    }

}
