// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats90
    {
#pragma warning disable 0649

        public Ie91 ie;
        public Edge91 edge;
        public Firefox91 firefox;
        public Chrome91 chrome;
        public Safari91 safari;
        public Opera91 opera;
        public IosSaf91 ios_saf;
        public OpMini91 op_mini;
        public Android91 android;
        public Bb91 bb;
        public OpMob91 op_mob;
        public AndChr91 and_chr;
        public AndFf91 and_ff;
        public IeMob91 ie_mob;
        public AndUc91 and_uc;

#pragma warning restore 0649

    }

}
