// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats70
    {
#pragma warning disable 0649

        public Ie71 ie;
        public Edge71 edge;
        public Firefox71 firefox;
        public Chrome71 chrome;
        public Safari71 safari;
        public Opera71 opera;
        public IosSaf71 ios_saf;
        public OpMini71 op_mini;
        public Android71 android;
        public Bb71 bb;
        public OpMob71 op_mob;
        public AndChr71 and_chr;
        public AndFf71 and_ff;
        public IeMob71 ie_mob;
        public AndUc71 and_uc;

#pragma warning restore 0649

    }

}
