// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats53
    {
#pragma warning disable 0649

        public Ie54 ie;
        public Edge54 edge;
        public Firefox54 firefox;
        public Chrome54 chrome;
        public Safari54 safari;
        public Opera54 opera;
        public IosSaf54 ios_saf;
        public OpMini54 op_mini;
        public Android54 android;
        public Bb54 bb;
        public OpMob54 op_mob;
        public AndChr54 and_chr;
        public AndFf54 and_ff;
        public IeMob54 ie_mob;
        public AndUc54 and_uc;

#pragma warning restore 0649

    }

}
