// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats164
    {
#pragma warning disable 0649

        public Ie165 ie;
        public Edge165 edge;
        public Firefox165 firefox;
        public Chrome165 chrome;
        public Safari165 safari;
        public Opera165 opera;
        public IosSaf165 ios_saf;
        public OpMini165 op_mini;
        public Android165 android;
        public Bb165 bb;
        public OpMob165 op_mob;
        public AndChr165 and_chr;
        public AndFf165 and_ff;
        public IeMob165 ie_mob;
        public AndUc165 and_uc;

#pragma warning restore 0649

    }

}
