// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats277
    {
#pragma warning disable 0649

        public Ie278 ie;
        public Edge278 edge;
        public Firefox278 firefox;
        public Chrome278 chrome;
        public Safari278 safari;
        public Opera278 opera;
        public IosSaf278 ios_saf;
        public OpMini278 op_mini;
        public Android278 android;
        public Bb278 bb;
        public OpMob278 op_mob;
        public AndChr278 and_chr;
        public AndFf278 and_ff;
        public IeMob278 ie_mob;
        public AndUc278 and_uc;

#pragma warning restore 0649

    }

}
