// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats189
    {
#pragma warning disable 0649

        public Ie190 ie;
        public Edge190 edge;
        public Firefox190 firefox;
        public Chrome190 chrome;
        public Safari190 safari;
        public Opera190 opera;
        public IosSaf190 ios_saf;
        public OpMini190 op_mini;
        public Android190 android;
        public Bb190 bb;
        public OpMob190 op_mob;
        public AndChr190 and_chr;
        public AndFf190 and_ff;
        public IeMob190 ie_mob;
        public AndUc190 and_uc;

#pragma warning restore 0649

    }

}
