// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats241
    {
#pragma warning disable 0649

        public Ie242 ie;
        public Edge242 edge;
        public Firefox242 firefox;
        public Chrome242 chrome;
        public Safari242 safari;
        public Opera242 opera;
        public IosSaf242 ios_saf;
        public OpMini242 op_mini;
        public Android242 android;
        public Bb242 bb;
        public OpMob242 op_mob;
        public AndChr242 and_chr;
        public AndFf242 and_ff;
        public IeMob242 ie_mob;
        public AndUc242 and_uc;

#pragma warning restore 0649

    }

}
