// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats136
    {
#pragma warning disable 0649

        public Ie137 ie;
        public Edge137 edge;
        public Firefox137 firefox;
        public Chrome137 chrome;
        public Safari137 safari;
        public Opera137 opera;
        public IosSaf137 ios_saf;
        public OpMini137 op_mini;
        public Android137 android;
        public Bb137 bb;
        public OpMob137 op_mob;
        public AndChr137 and_chr;
        public AndFf137 and_ff;
        public IeMob137 ie_mob;
        public AndUc137 and_uc;

#pragma warning restore 0649

    }

}
