// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats25
    {
#pragma warning disable 0649

        public Ie26 ie;
        public Edge26 edge;
        public Firefox26 firefox;
        public Chrome26 chrome;
        public Safari26 safari;
        public Opera26 opera;
        public IosSaf26 ios_saf;
        public OpMini26 op_mini;
        public Android26 android;
        public Bb26 bb;
        public OpMob26 op_mob;
        public AndChr26 and_chr;
        public AndFf26 and_ff;
        public IeMob26 ie_mob;
        public AndUc26 and_uc;

#pragma warning restore 0649

    }

}
