// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats279
    {
#pragma warning disable 0649

        public Ie280 ie;
        public Edge280 edge;
        public Firefox280 firefox;
        public Chrome280 chrome;
        public Safari280 safari;
        public Opera280 opera;
        public IosSaf280 ios_saf;
        public OpMini280 op_mini;
        public Android280 android;
        public Bb280 bb;
        public OpMob280 op_mob;
        public AndChr280 and_chr;
        public AndFf280 and_ff;
        public IeMob280 ie_mob;
        public AndUc280 and_uc;

#pragma warning restore 0649

    }

}
