// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats114
    {
#pragma warning disable 0649

        public Ie115 ie;
        public Edge115 edge;
        public Firefox115 firefox;
        public Chrome115 chrome;
        public Safari115 safari;
        public Opera115 opera;
        public IosSaf115 ios_saf;
        public OpMini115 op_mini;
        public Android115 android;
        public Bb115 bb;
        public OpMob115 op_mob;
        public AndChr115 and_chr;
        public AndFf115 and_ff;
        public IeMob115 ie_mob;
        public AndUc115 and_uc;

#pragma warning restore 0649

    }

}
