// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats204
    {
#pragma warning disable 0649

        public Ie205 ie;
        public Edge205 edge;
        public Firefox205 firefox;
        public Chrome205 chrome;
        public Safari205 safari;
        public Opera205 opera;
        public IosSaf205 ios_saf;
        public OpMini205 op_mini;
        public Android205 android;
        public Bb205 bb;
        public OpMob205 op_mob;
        public AndChr205 and_chr;
        public AndFf205 and_ff;
        public IeMob205 ie_mob;
        public AndUc205 and_uc;

#pragma warning restore 0649

    }

}
