// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats17
    {
#pragma warning disable 0649

        public Ie18 ie;
        public Edge18 edge;
        public Firefox18 firefox;
        public Chrome18 chrome;
        public Safari18 safari;
        public Opera18 opera;
        public IosSaf18 ios_saf;
        public OpMini18 op_mini;
        public Android18 android;
        public Bb18 bb;
        public OpMob18 op_mob;
        public AndChr18 and_chr;
        public AndFf18 and_ff;
        public IeMob18 ie_mob;
        public AndUc18 and_uc;

#pragma warning restore 0649

    }

}
