// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats273
    {
#pragma warning disable 0649

        public Ie274 ie;
        public Edge274 edge;
        public Firefox274 firefox;
        public Chrome274 chrome;
        public Safari274 safari;
        public Opera274 opera;
        public IosSaf274 ios_saf;
        public OpMini274 op_mini;
        public Android274 android;
        public Bb274 bb;
        public OpMob274 op_mob;
        public AndChr274 and_chr;
        public AndFf274 and_ff;
        public IeMob274 ie_mob;
        public AndUc274 and_uc;

#pragma warning restore 0649

    }

}
