// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats210
    {
#pragma warning disable 0649

        public Ie211 ie;
        public Edge211 edge;
        public Firefox211 firefox;
        public Chrome211 chrome;
        public Safari211 safari;
        public Opera211 opera;
        public IosSaf211 ios_saf;
        public OpMini211 op_mini;
        public Android211 android;
        public Bb211 bb;
        public OpMob211 op_mob;
        public AndChr211 and_chr;
        public AndFf211 and_ff;
        public IeMob211 ie_mob;
        public AndUc211 and_uc;

#pragma warning restore 0649

    }

}
