// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats285
    {
#pragma warning disable 0649

        public Ie286 ie;
        public Edge286 edge;
        public Firefox286 firefox;
        public Chrome286 chrome;
        public Safari286 safari;
        public Opera286 opera;
        public IosSaf286 ios_saf;
        public OpMini286 op_mini;
        public Android286 android;
        public Bb286 bb;
        public OpMob286 op_mob;
        public AndChr286 and_chr;
        public AndFf286 and_ff;
        public IeMob286 ie_mob;
        public AndUc286 and_uc;

#pragma warning restore 0649

    }

}
