// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats247
    {
#pragma warning disable 0649

        public Ie248 ie;
        public Edge248 edge;
        public Firefox248 firefox;
        public Chrome248 chrome;
        public Safari248 safari;
        public Opera248 opera;
        public IosSaf248 ios_saf;
        public OpMini248 op_mini;
        public Android248 android;
        public Bb248 bb;
        public OpMob248 op_mob;
        public AndChr248 and_chr;
        public AndFf248 and_ff;
        public IeMob248 ie_mob;
        public AndUc248 and_uc;

#pragma warning restore 0649

    }

}
