// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats205
    {
#pragma warning disable 0649

        public Ie206 ie;
        public Edge206 edge;
        public Firefox206 firefox;
        public Chrome206 chrome;
        public Safari206 safari;
        public Opera206 opera;
        public IosSaf206 ios_saf;
        public OpMini206 op_mini;
        public Android206 android;
        public Bb206 bb;
        public OpMob206 op_mob;
        public AndChr206 and_chr;
        public AndFf206 and_ff;
        public IeMob206 ie_mob;
        public AndUc206 and_uc;

#pragma warning restore 0649

    }

}
