// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats243
    {
#pragma warning disable 0649

        public Ie244 ie;
        public Edge244 edge;
        public Firefox244 firefox;
        public Chrome244 chrome;
        public Safari244 safari;
        public Opera244 opera;
        public IosSaf244 ios_saf;
        public OpMini244 op_mini;
        public Android244 android;
        public Bb244 bb;
        public OpMob244 op_mob;
        public AndChr244 and_chr;
        public AndFf244 and_ff;
        public IeMob244 ie_mob;
        public AndUc244 and_uc;

#pragma warning restore 0649

    }

}
