// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats275
    {
#pragma warning disable 0649

        public Ie276 ie;
        public Edge276 edge;
        public Firefox276 firefox;
        public Chrome276 chrome;
        public Safari276 safari;
        public Opera276 opera;
        public IosSaf276 ios_saf;
        public OpMini276 op_mini;
        public Android276 android;
        public Bb276 bb;
        public OpMob276 op_mob;
        public AndChr276 and_chr;
        public AndFf276 and_ff;
        public IeMob276 ie_mob;
        public AndUc276 and_uc;

#pragma warning restore 0649

    }

}
