// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats125
    {
#pragma warning disable 0649

        public Ie126 ie;
        public Edge126 edge;
        public Firefox126 firefox;
        public Chrome126 chrome;
        public Safari126 safari;
        public Opera126 opera;
        public IosSaf126 ios_saf;
        public OpMini126 op_mini;
        public Android126 android;
        public Bb126 bb;
        public OpMob126 op_mob;
        public AndChr126 and_chr;
        public AndFf126 and_ff;
        public IeMob126 ie_mob;
        public AndUc126 and_uc;

#pragma warning restore 0649

    }

}
