// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats21
    {
#pragma warning disable 0649

        public Ie22 ie;
        public Edge22 edge;
        public Firefox22 firefox;
        public Chrome22 chrome;
        public Safari22 safari;
        public Opera22 opera;
        public IosSaf22 ios_saf;
        public OpMini22 op_mini;
        public Android22 android;
        public Bb22 bb;
        public OpMob22 op_mob;
        public AndChr22 and_chr;
        public AndFf22 and_ff;
        public IeMob22 ie_mob;
        public AndUc22 and_uc;

#pragma warning restore 0649

    }

}
