// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats147
    {
#pragma warning disable 0649

        public Ie148 ie;
        public Edge148 edge;
        public Firefox148 firefox;
        public Chrome148 chrome;
        public Safari148 safari;
        public Opera148 opera;
        public IosSaf148 ios_saf;
        public OpMini148 op_mini;
        public Android148 android;
        public Bb148 bb;
        public OpMob148 op_mob;
        public AndChr148 and_chr;
        public AndFf148 and_ff;
        public IeMob148 ie_mob;
        public AndUc148 and_uc;

#pragma warning restore 0649

    }

}
