// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats218
    {
#pragma warning disable 0649

        public Ie219 ie;
        public Edge219 edge;
        public Firefox219 firefox;
        public Chrome219 chrome;
        public Safari219 safari;
        public Opera219 opera;
        public IosSaf219 ios_saf;
        public OpMini219 op_mini;
        public Android219 android;
        public Bb219 bb;
        public OpMob219 op_mob;
        public AndChr219 and_chr;
        public AndFf219 and_ff;
        public IeMob219 ie_mob;
        public AndUc219 and_uc;

#pragma warning restore 0649

    }

}
