// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats173
    {
#pragma warning disable 0649

        public Ie174 ie;
        public Edge174 edge;
        public Firefox174 firefox;
        public Chrome174 chrome;
        public Safari174 safari;
        public Opera174 opera;
        public IosSaf174 ios_saf;
        public OpMini174 op_mini;
        public Android174 android;
        public Bb174 bb;
        public OpMob174 op_mob;
        public AndChr174 and_chr;
        public AndFf174 and_ff;
        public IeMob174 ie_mob;
        public AndUc174 and_uc;

#pragma warning restore 0649

    }

}
