// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats267
    {
#pragma warning disable 0649

        public Ie268 ie;
        public Edge268 edge;
        public Firefox268 firefox;
        public Chrome268 chrome;
        public Safari268 safari;
        public Opera268 opera;
        public IosSaf268 ios_saf;
        public OpMini268 op_mini;
        public Android268 android;
        public Bb268 bb;
        public OpMob268 op_mob;
        public AndChr268 and_chr;
        public AndFf268 and_ff;
        public IeMob268 ie_mob;
        public AndUc268 and_uc;

#pragma warning restore 0649

    }

}
