// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats268
    {
#pragma warning disable 0649

        public Ie269 ie;
        public Edge269 edge;
        public Firefox269 firefox;
        public Chrome269 chrome;
        public Safari269 safari;
        public Opera269 opera;
        public IosSaf269 ios_saf;
        public OpMini269 op_mini;
        public Android269 android;
        public Bb269 bb;
        public OpMob269 op_mob;
        public AndChr269 and_chr;
        public AndFf269 and_ff;
        public IeMob269 ie_mob;
        public AndUc269 and_uc;

#pragma warning restore 0649

    }

}
