// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats199
    {
#pragma warning disable 0649

        public Ie200 ie;
        public Edge200 edge;
        public Firefox200 firefox;
        public Chrome200 chrome;
        public Safari200 safari;
        public Opera200 opera;
        public IosSaf200 ios_saf;
        public OpMini200 op_mini;
        public Android200 android;
        public Bb200 bb;
        public OpMob200 op_mob;
        public AndChr200 and_chr;
        public AndFf200 and_ff;
        public IeMob200 ie_mob;
        public AndUc200 and_uc;

#pragma warning restore 0649

    }

}
