// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats195
    {
#pragma warning disable 0649

        public Ie196 ie;
        public Edge196 edge;
        public Firefox196 firefox;
        public Chrome196 chrome;
        public Safari196 safari;
        public Opera196 opera;
        public IosSaf196 ios_saf;
        public OpMini196 op_mini;
        public Android196 android;
        public Bb196 bb;
        public OpMob196 op_mob;
        public AndChr196 and_chr;
        public AndFf196 and_ff;
        public IeMob196 ie_mob;
        public AndUc196 and_uc;

#pragma warning restore 0649

    }

}
