// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats272
    {
#pragma warning disable 0649

        public Ie273 ie;
        public Edge273 edge;
        public Firefox273 firefox;
        public Chrome273 chrome;
        public Safari273 safari;
        public Opera273 opera;
        public IosSaf273 ios_saf;
        public OpMini273 op_mini;
        public Android273 android;
        public Bb273 bb;
        public OpMob273 op_mob;
        public AndChr273 and_chr;
        public AndFf273 and_ff;
        public IeMob273 ie_mob;
        public AndUc273 and_uc;

#pragma warning restore 0649

    }

}
