// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats203
    {
#pragma warning disable 0649

        public Ie204 ie;
        public Edge204 edge;
        public Firefox204 firefox;
        public Chrome204 chrome;
        public Safari204 safari;
        public Opera204 opera;
        public IosSaf204 ios_saf;
        public OpMini204 op_mini;
        public Android204 android;
        public Bb204 bb;
        public OpMob204 op_mob;
        public AndChr204 and_chr;
        public AndFf204 and_ff;
        public IeMob204 ie_mob;
        public AndUc204 and_uc;

#pragma warning restore 0649

    }

}
