// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats130
    {
#pragma warning disable 0649

        public Ie131 ie;
        public Edge131 edge;
        public Firefox131 firefox;
        public Chrome131 chrome;
        public Safari131 safari;
        public Opera131 opera;
        public IosSaf131 ios_saf;
        public OpMini131 op_mini;
        public Android131 android;
        public Bb131 bb;
        public OpMob131 op_mob;
        public AndChr131 and_chr;
        public AndFf131 and_ff;
        public IeMob131 ie_mob;
        public AndUc131 and_uc;

#pragma warning restore 0649

    }

}
