// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats68
    {
#pragma warning disable 0649

        public Ie69 ie;
        public Edge69 edge;
        public Firefox69 firefox;
        public Chrome69 chrome;
        public Safari69 safari;
        public Opera69 opera;
        public IosSaf69 ios_saf;
        public OpMini69 op_mini;
        public Android69 android;
        public Bb69 bb;
        public OpMob69 op_mob;
        public AndChr69 and_chr;
        public AndFf69 and_ff;
        public IeMob69 ie_mob;
        public AndUc69 and_uc;

#pragma warning restore 0649

    }

}
