// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats169
    {
#pragma warning disable 0649

        public Ie170 ie;
        public Edge170 edge;
        public Firefox170 firefox;
        public Chrome170 chrome;
        public Safari170 safari;
        public Opera170 opera;
        public IosSaf170 ios_saf;
        public OpMini170 op_mini;
        public Android170 android;
        public Bb170 bb;
        public OpMob170 op_mob;
        public AndChr170 and_chr;
        public AndFf170 and_ff;
        public IeMob170 ie_mob;
        public AndUc170 and_uc;

#pragma warning restore 0649

    }

}
