// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats253
    {
#pragma warning disable 0649

        public Ie254 ie;
        public Edge254 edge;
        public Firefox254 firefox;
        public Chrome254 chrome;
        public Safari254 safari;
        public Opera254 opera;
        public IosSaf254 ios_saf;
        public OpMini254 op_mini;
        public Android254 android;
        public Bb254 bb;
        public OpMob254 op_mob;
        public AndChr254 and_chr;
        public AndFf254 and_ff;
        public IeMob254 ie_mob;
        public AndUc254 and_uc;

#pragma warning restore 0649

    }

}
