// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats265
    {
#pragma warning disable 0649

        public Ie266 ie;
        public Edge266 edge;
        public Firefox266 firefox;
        public Chrome266 chrome;
        public Safari266 safari;
        public Opera266 opera;
        public IosSaf266 ios_saf;
        public OpMini266 op_mini;
        public Android266 android;
        public Bb266 bb;
        public OpMob266 op_mob;
        public AndChr266 and_chr;
        public AndFf266 and_ff;
        public IeMob266 ie_mob;
        public AndUc266 and_uc;

#pragma warning restore 0649

    }

}
