// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats259
    {
#pragma warning disable 0649

        public Ie260 ie;
        public Edge260 edge;
        public Firefox260 firefox;
        public Chrome260 chrome;
        public Safari260 safari;
        public Opera260 opera;
        public IosSaf260 ios_saf;
        public OpMini260 op_mini;
        public Android260 android;
        public Bb260 bb;
        public OpMob260 op_mob;
        public AndChr260 and_chr;
        public AndFf260 and_ff;
        public IeMob260 ie_mob;
        public AndUc260 and_uc;

#pragma warning restore 0649

    }

}
