// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats35
    {
#pragma warning disable 0649

        public Ie36 ie;
        public Edge36 edge;
        public Firefox36 firefox;
        public Chrome36 chrome;
        public Safari36 safari;
        public Opera36 opera;
        public IosSaf36 ios_saf;
        public OpMini36 op_mini;
        public Android36 android;
        public Bb36 bb;
        public OpMob36 op_mob;
        public AndChr36 and_chr;
        public AndFf36 and_ff;
        public IeMob36 ie_mob;
        public AndUc36 and_uc;

#pragma warning restore 0649

    }

}
