// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats244
    {
#pragma warning disable 0649

        public Ie245 ie;
        public Edge245 edge;
        public Firefox245 firefox;
        public Chrome245 chrome;
        public Safari245 safari;
        public Opera245 opera;
        public IosSaf245 ios_saf;
        public OpMini245 op_mini;
        public Android245 android;
        public Bb245 bb;
        public OpMob245 op_mob;
        public AndChr245 and_chr;
        public AndFf245 and_ff;
        public IeMob245 ie_mob;
        public AndUc245 and_uc;

#pragma warning restore 0649

    }

}
