// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats155
    {
#pragma warning disable 0649

        public Ie156 ie;
        public Edge156 edge;
        public Firefox156 firefox;
        public Chrome156 chrome;
        public Safari156 safari;
        public Opera156 opera;
        public IosSaf156 ios_saf;
        public OpMini156 op_mini;
        public Android156 android;
        public Bb156 bb;
        public OpMob156 op_mob;
        public AndChr156 and_chr;
        public AndFf156 and_ff;
        public IeMob156 ie_mob;
        public AndUc156 and_uc;

#pragma warning restore 0649

    }

}
