// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats192
    {
#pragma warning disable 0649

        public Ie193 ie;
        public Edge193 edge;
        public Firefox193 firefox;
        public Chrome193 chrome;
        public Safari193 safari;
        public Opera193 opera;
        public IosSaf193 ios_saf;
        public OpMini193 op_mini;
        public Android193 android;
        public Bb193 bb;
        public OpMob193 op_mob;
        public AndChr193 and_chr;
        public AndFf193 and_ff;
        public IeMob193 ie_mob;
        public AndUc193 and_uc;

#pragma warning restore 0649

    }

}
