// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats22
    {
#pragma warning disable 0649

        public Ie23 ie;
        public Edge23 edge;
        public Firefox23 firefox;
        public Chrome23 chrome;
        public Safari23 safari;
        public Opera23 opera;
        public IosSaf23 ios_saf;
        public OpMini23 op_mini;
        public Android23 android;
        public Bb23 bb;
        public OpMob23 op_mob;
        public AndChr23 and_chr;
        public AndFf23 and_ff;
        public IeMob23 ie_mob;
        public AndUc23 and_uc;

#pragma warning restore 0649

    }

}
