// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats135
    {
#pragma warning disable 0649

        public Ie136 ie;
        public Edge136 edge;
        public Firefox136 firefox;
        public Chrome136 chrome;
        public Safari136 safari;
        public Opera136 opera;
        public IosSaf136 ios_saf;
        public OpMini136 op_mini;
        public Android136 android;
        public Bb136 bb;
        public OpMob136 op_mob;
        public AndChr136 and_chr;
        public AndFf136 and_ff;
        public IeMob136 ie_mob;
        public AndUc136 and_uc;

#pragma warning restore 0649

    }

}
