// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats107
    {
#pragma warning disable 0649

        public Ie108 ie;
        public Edge108 edge;
        public Firefox108 firefox;
        public Chrome108 chrome;
        public Safari108 safari;
        public Opera108 opera;
        public IosSaf108 ios_saf;
        public OpMini108 op_mini;
        public Android108 android;
        public Bb108 bb;
        public OpMob108 op_mob;
        public AndChr108 and_chr;
        public AndFf108 and_ff;
        public IeMob108 ie_mob;
        public AndUc108 and_uc;

#pragma warning restore 0649

    }

}
