// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats84
    {
#pragma warning disable 0649

        public Ie85 ie;
        public Edge85 edge;
        public Firefox85 firefox;
        public Chrome85 chrome;
        public Safari85 safari;
        public Opera85 opera;
        public IosSaf85 ios_saf;
        public OpMini85 op_mini;
        public Android85 android;
        public Bb85 bb;
        public OpMob85 op_mob;
        public AndChr85 and_chr;
        public AndFf85 and_ff;
        public IeMob85 ie_mob;
        public AndUc85 and_uc;

#pragma warning restore 0649

    }

}
