// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats117
    {
#pragma warning disable 0649

        public Ie118 ie;
        public Edge118 edge;
        public Firefox118 firefox;
        public Chrome118 chrome;
        public Safari118 safari;
        public Opera118 opera;
        public IosSaf118 ios_saf;
        public OpMini118 op_mini;
        public Android118 android;
        public Bb118 bb;
        public OpMob118 op_mob;
        public AndChr118 and_chr;
        public AndFf118 and_ff;
        public IeMob118 ie_mob;
        public AndUc118 and_uc;

#pragma warning restore 0649

    }

}
