// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats227
    {
#pragma warning disable 0649

        public Ie228 ie;
        public Edge228 edge;
        public Firefox228 firefox;
        public Chrome228 chrome;
        public Safari228 safari;
        public Opera228 opera;
        public IosSaf228 ios_saf;
        public OpMini228 op_mini;
        public Android228 android;
        public Bb228 bb;
        public OpMob228 op_mob;
        public AndChr228 and_chr;
        public AndFf228 and_ff;
        public IeMob228 ie_mob;
        public AndUc228 and_uc;

#pragma warning restore 0649

    }

}
