// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats170
    {
#pragma warning disable 0649

        public Ie171 ie;
        public Edge171 edge;
        public Firefox171 firefox;
        public Chrome171 chrome;
        public Safari171 safari;
        public Opera171 opera;
        public IosSaf171 ios_saf;
        public OpMini171 op_mini;
        public Android171 android;
        public Bb171 bb;
        public OpMob171 op_mob;
        public AndChr171 and_chr;
        public AndFf171 and_ff;
        public IeMob171 ie_mob;
        public AndUc171 and_uc;

#pragma warning restore 0649

    }

}
