// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats151
    {
#pragma warning disable 0649

        public Ie152 ie;
        public Edge152 edge;
        public Firefox152 firefox;
        public Chrome152 chrome;
        public Safari152 safari;
        public Opera152 opera;
        public IosSaf152 ios_saf;
        public OpMini152 op_mini;
        public Android152 android;
        public Bb152 bb;
        public OpMob152 op_mob;
        public AndChr152 and_chr;
        public AndFf152 and_ff;
        public IeMob152 ie_mob;
        public AndUc152 and_uc;

#pragma warning restore 0649

    }

}
