// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats266
    {
#pragma warning disable 0649

        public Ie267 ie;
        public Edge267 edge;
        public Firefox267 firefox;
        public Chrome267 chrome;
        public Safari267 safari;
        public Opera267 opera;
        public IosSaf267 ios_saf;
        public OpMini267 op_mini;
        public Android267 android;
        public Bb267 bb;
        public OpMob267 op_mob;
        public AndChr267 and_chr;
        public AndFf267 and_ff;
        public IeMob267 ie_mob;
        public AndUc267 and_uc;

#pragma warning restore 0649

    }

}
