// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats43
    {
#pragma warning disable 0649

        public Ie44 ie;
        public Edge44 edge;
        public Firefox44 firefox;
        public Chrome44 chrome;
        public Safari44 safari;
        public Opera44 opera;
        public IosSaf44 ios_saf;
        public OpMini44 op_mini;
        public Android44 android;
        public Bb44 bb;
        public OpMob44 op_mob;
        public AndChr44 and_chr;
        public AndFf44 and_ff;
        public IeMob44 ie_mob;
        public AndUc44 and_uc;

#pragma warning restore 0649

    }

}
