// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats232
    {
#pragma warning disable 0649

        public Ie233 ie;
        public Edge233 edge;
        public Firefox233 firefox;
        public Chrome233 chrome;
        public Safari233 safari;
        public Opera233 opera;
        public IosSaf233 ios_saf;
        public OpMini233 op_mini;
        public Android233 android;
        public Bb233 bb;
        public OpMob233 op_mob;
        public AndChr233 and_chr;
        public AndFf233 and_ff;
        public IeMob233 ie_mob;
        public AndUc233 and_uc;

#pragma warning restore 0649

    }

}
