// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats98
    {
#pragma warning disable 0649

        public Ie99 ie;
        public Edge99 edge;
        public Firefox99 firefox;
        public Chrome99 chrome;
        public Safari99 safari;
        public Opera99 opera;
        public IosSaf99 ios_saf;
        public OpMini99 op_mini;
        public Android99 android;
        public Bb99 bb;
        public OpMob99 op_mob;
        public AndChr99 and_chr;
        public AndFf99 and_ff;
        public IeMob99 ie_mob;
        public AndUc99 and_uc;

#pragma warning restore 0649

    }

}
