// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats16
    {
#pragma warning disable 0649

        public Ie17 ie;
        public Edge17 edge;
        public Firefox17 firefox;
        public Chrome17 chrome;
        public Safari17 safari;
        public Opera17 opera;
        public IosSaf17 ios_saf;
        public OpMini17 op_mini;
        public Android17 android;
        public Bb17 bb;
        public OpMob17 op_mob;
        public AndChr17 and_chr;
        public AndFf17 and_ff;
        public IeMob17 ie_mob;
        public AndUc17 and_uc;

#pragma warning restore 0649

    }

}
