// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats215
    {
#pragma warning disable 0649

        public Ie216 ie;
        public Edge216 edge;
        public Firefox216 firefox;
        public Chrome216 chrome;
        public Safari216 safari;
        public Opera216 opera;
        public IosSaf216 ios_saf;
        public OpMini216 op_mini;
        public Android216 android;
        public Bb216 bb;
        public OpMob216 op_mob;
        public AndChr216 and_chr;
        public AndFf216 and_ff;
        public IeMob216 ie_mob;
        public AndUc216 and_uc;

#pragma warning restore 0649

    }

}
