// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats92
    {
#pragma warning disable 0649

        public Ie93 ie;
        public Edge93 edge;
        public Firefox93 firefox;
        public Chrome93 chrome;
        public Safari93 safari;
        public Opera93 opera;
        public IosSaf93 ios_saf;
        public OpMini93 op_mini;
        public Android93 android;
        public Bb93 bb;
        public OpMob93 op_mob;
        public AndChr93 and_chr;
        public AndFf93 and_ff;
        public IeMob93 ie_mob;
        public AndUc93 and_uc;

#pragma warning restore 0649

    }

}
