// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats46
    {
#pragma warning disable 0649

        public Ie47 ie;
        public Edge47 edge;
        public Firefox47 firefox;
        public Chrome47 chrome;
        public Safari47 safari;
        public Opera47 opera;
        public IosSaf47 ios_saf;
        public OpMini47 op_mini;
        public Android47 android;
        public Bb47 bb;
        public OpMob47 op_mob;
        public AndChr47 and_chr;
        public AndFf47 and_ff;
        public IeMob47 ie_mob;
        public AndUc47 and_uc;

#pragma warning restore 0649

    }

}
