// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats13
    {
#pragma warning disable 0649

        public Ie14 ie;
        public Edge14 edge;
        public Firefox14 firefox;
        public Chrome14 chrome;
        public Safari14 safari;
        public Opera14 opera;
        public IosSaf14 ios_saf;
        public OpMini14 op_mini;
        public Android14 android;
        public Bb14 bb;
        public OpMob14 op_mob;
        public AndChr14 and_chr;
        public AndFf14 and_ff;
        public IeMob14 ie_mob;
        public AndUc14 and_uc;

#pragma warning restore 0649

    }

}
