// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats33
    {
#pragma warning disable 0649

        public Ie34 ie;
        public Edge34 edge;
        public Firefox34 firefox;
        public Chrome34 chrome;
        public Safari34 safari;
        public Opera34 opera;
        public IosSaf34 ios_saf;
        public OpMini34 op_mini;
        public Android34 android;
        public Bb34 bb;
        public OpMob34 op_mob;
        public AndChr34 and_chr;
        public AndFf34 and_ff;
        public IeMob34 ie_mob;
        public AndUc34 and_uc;

#pragma warning restore 0649

    }

}
