// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats255
    {
#pragma warning disable 0649

        public Ie256 ie;
        public Edge256 edge;
        public Firefox256 firefox;
        public Chrome256 chrome;
        public Safari256 safari;
        public Opera256 opera;
        public IosSaf256 ios_saf;
        public OpMini256 op_mini;
        public Android256 android;
        public Bb256 bb;
        public OpMob256 op_mob;
        public AndChr256 and_chr;
        public AndFf256 and_ff;
        public IeMob256 ie_mob;
        public AndUc256 and_uc;

#pragma warning restore 0649

    }

}
