// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats284
    {
#pragma warning disable 0649

        public Ie285 ie;
        public Edge285 edge;
        public Firefox285 firefox;
        public Chrome285 chrome;
        public Safari285 safari;
        public Opera285 opera;
        public IosSaf285 ios_saf;
        public OpMini285 op_mini;
        public Android285 android;
        public Bb285 bb;
        public OpMob285 op_mob;
        public AndChr285 and_chr;
        public AndFf285 and_ff;
        public IeMob285 ie_mob;
        public AndUc285 and_uc;

#pragma warning restore 0649

    }

}
