// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats20
    {
#pragma warning disable 0649

        public Ie21 ie;
        public Edge21 edge;
        public Firefox21 firefox;
        public Chrome21 chrome;
        public Safari21 safari;
        public Opera21 opera;
        public IosSaf21 ios_saf;
        public OpMini21 op_mini;
        public Android21 android;
        public Bb21 bb;
        public OpMob21 op_mob;
        public AndChr21 and_chr;
        public AndFf21 and_ff;
        public IeMob21 ie_mob;
        public AndUc21 and_uc;

#pragma warning restore 0649

    }

}
