// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats223
    {
#pragma warning disable 0649

        public Ie224 ie;
        public Edge224 edge;
        public Firefox224 firefox;
        public Chrome224 chrome;
        public Safari224 safari;
        public Opera224 opera;
        public IosSaf224 ios_saf;
        public OpMini224 op_mini;
        public Android224 android;
        public Bb224 bb;
        public OpMob224 op_mob;
        public AndChr224 and_chr;
        public AndFf224 and_ff;
        public IeMob224 ie_mob;
        public AndUc224 and_uc;

#pragma warning restore 0649

    }

}
