// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats245
    {
#pragma warning disable 0649

        public Ie246 ie;
        public Edge246 edge;
        public Firefox246 firefox;
        public Chrome246 chrome;
        public Safari246 safari;
        public Opera246 opera;
        public IosSaf246 ios_saf;
        public OpMini246 op_mini;
        public Android246 android;
        public Bb246 bb;
        public OpMob246 op_mob;
        public AndChr246 and_chr;
        public AndFf246 and_ff;
        public IeMob246 ie_mob;
        public AndUc246 and_uc;

#pragma warning restore 0649

    }

}
