// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats196
    {
#pragma warning disable 0649

        public Ie197 ie;
        public Edge197 edge;
        public Firefox197 firefox;
        public Chrome197 chrome;
        public Safari197 safari;
        public Opera197 opera;
        public IosSaf197 ios_saf;
        public OpMini197 op_mini;
        public Android197 android;
        public Bb197 bb;
        public OpMob197 op_mob;
        public AndChr197 and_chr;
        public AndFf197 and_ff;
        public IeMob197 ie_mob;
        public AndUc197 and_uc;

#pragma warning restore 0649

    }

}
