// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats163
    {
#pragma warning disable 0649

        public Ie164 ie;
        public Edge164 edge;
        public Firefox164 firefox;
        public Chrome164 chrome;
        public Safari164 safari;
        public Opera164 opera;
        public IosSaf164 ios_saf;
        public OpMini164 op_mini;
        public Android164 android;
        public Bb164 bb;
        public OpMob164 op_mob;
        public AndChr164 and_chr;
        public AndFf164 and_ff;
        public IeMob164 ie_mob;
        public AndUc164 and_uc;

#pragma warning restore 0649

    }

}
