// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats28
    {
#pragma warning disable 0649

        public Ie29 ie;
        public Edge29 edge;
        public Firefox29 firefox;
        public Chrome29 chrome;
        public Safari29 safari;
        public Opera29 opera;
        public IosSaf29 ios_saf;
        public OpMini29 op_mini;
        public Android29 android;
        public Bb29 bb;
        public OpMob29 op_mob;
        public AndChr29 and_chr;
        public AndFf29 and_ff;
        public IeMob29 ie_mob;
        public AndUc29 and_uc;

#pragma warning restore 0649

    }

}
