// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats278
    {
#pragma warning disable 0649

        public Ie279 ie;
        public Edge279 edge;
        public Firefox279 firefox;
        public Chrome279 chrome;
        public Safari279 safari;
        public Opera279 opera;
        public IosSaf279 ios_saf;
        public OpMini279 op_mini;
        public Android279 android;
        public Bb279 bb;
        public OpMob279 op_mob;
        public AndChr279 and_chr;
        public AndFf279 and_ff;
        public IeMob279 ie_mob;
        public AndUc279 and_uc;

#pragma warning restore 0649

    }

}
