// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats274
    {
#pragma warning disable 0649

        public Ie275 ie;
        public Edge275 edge;
        public Firefox275 firefox;
        public Chrome275 chrome;
        public Safari275 safari;
        public Opera275 opera;
        public IosSaf275 ios_saf;
        public OpMini275 op_mini;
        public Android275 android;
        public Bb275 bb;
        public OpMob275 op_mob;
        public AndChr275 and_chr;
        public AndFf275 and_ff;
        public IeMob275 ie_mob;
        public AndUc275 and_uc;

#pragma warning restore 0649

    }

}
