// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats54
    {
#pragma warning disable 0649

        public Ie55 ie;
        public Edge55 edge;
        public Firefox55 firefox;
        public Chrome55 chrome;
        public Safari55 safari;
        public Opera55 opera;
        public IosSaf55 ios_saf;
        public OpMini55 op_mini;
        public Android55 android;
        public Bb55 bb;
        public OpMob55 op_mob;
        public AndChr55 and_chr;
        public AndFf55 and_ff;
        public IeMob55 ie_mob;
        public AndUc55 and_uc;

#pragma warning restore 0649

    }

}
