// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats200
    {
#pragma warning disable 0649

        public Ie201 ie;
        public Edge201 edge;
        public Firefox201 firefox;
        public Chrome201 chrome;
        public Safari201 safari;
        public Opera201 opera;
        public IosSaf201 ios_saf;
        public OpMini201 op_mini;
        public Android201 android;
        public Bb201 bb;
        public OpMob201 op_mob;
        public AndChr201 and_chr;
        public AndFf201 and_ff;
        public IeMob201 ie_mob;
        public AndUc201 and_uc;

#pragma warning restore 0649

    }

}
