// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats148
    {
#pragma warning disable 0649

        public Ie149 ie;
        public Edge149 edge;
        public Firefox149 firefox;
        public Chrome149 chrome;
        public Safari149 safari;
        public Opera149 opera;
        public IosSaf149 ios_saf;
        public OpMini149 op_mini;
        public Android149 android;
        public Bb149 bb;
        public OpMob149 op_mob;
        public AndChr149 and_chr;
        public AndFf149 and_ff;
        public IeMob149 ie_mob;
        public AndUc149 and_uc;

#pragma warning restore 0649

    }

}
