// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats156
    {
#pragma warning disable 0649

        public Ie157 ie;
        public Edge157 edge;
        public Firefox157 firefox;
        public Chrome157 chrome;
        public Safari157 safari;
        public Opera157 opera;
        public IosSaf157 ios_saf;
        public OpMini157 op_mini;
        public Android157 android;
        public Bb157 bb;
        public OpMob157 op_mob;
        public AndChr157 and_chr;
        public AndFf157 and_ff;
        public IeMob157 ie_mob;
        public AndUc157 and_uc;

#pragma warning restore 0649

    }

}
