// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats12
    {
#pragma warning disable 0649

        public Ie13 ie;
        public Edge13 edge;
        public Firefox13 firefox;
        public Chrome13 chrome;
        public Safari13 safari;
        public Opera13 opera;
        public IosSaf13 ios_saf;
        public OpMini13 op_mini;
        public Android13 android;
        public Bb13 bb;
        public OpMob13 op_mob;
        public AndChr13 and_chr;
        public AndFf13 and_ff;
        public IeMob13 ie_mob;
        public AndUc13 and_uc;

#pragma warning restore 0649

    }

}
