// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats236
    {
#pragma warning disable 0649

        public Ie237 ie;
        public Edge237 edge;
        public Firefox237 firefox;
        public Chrome237 chrome;
        public Safari237 safari;
        public Opera237 opera;
        public IosSaf237 ios_saf;
        public OpMini237 op_mini;
        public Android237 android;
        public Bb237 bb;
        public OpMob237 op_mob;
        public AndChr237 and_chr;
        public AndFf237 and_ff;
        public IeMob237 ie_mob;
        public AndUc237 and_uc;

#pragma warning restore 0649

    }

}
