// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats162
    {
#pragma warning disable 0649

        public Ie163 ie;
        public Edge163 edge;
        public Firefox163 firefox;
        public Chrome163 chrome;
        public Safari163 safari;
        public Opera163 opera;
        public IosSaf163 ios_saf;
        public OpMini163 op_mini;
        public Android163 android;
        public Bb163 bb;
        public OpMob163 op_mob;
        public AndChr163 and_chr;
        public AndFf163 and_ff;
        public IeMob163 ie_mob;
        public AndUc163 and_uc;

#pragma warning restore 0649

    }

}
