// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats276
    {
#pragma warning disable 0649

        public Ie277 ie;
        public Edge277 edge;
        public Firefox277 firefox;
        public Chrome277 chrome;
        public Safari277 safari;
        public Opera277 opera;
        public IosSaf277 ios_saf;
        public OpMini277 op_mini;
        public Android277 android;
        public Bb277 bb;
        public OpMob277 op_mob;
        public AndChr277 and_chr;
        public AndFf277 and_ff;
        public IeMob277 ie_mob;
        public AndUc277 and_uc;

#pragma warning restore 0649

    }

}
