// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats202
    {
#pragma warning disable 0649

        public Ie203 ie;
        public Edge203 edge;
        public Firefox203 firefox;
        public Chrome203 chrome;
        public Safari203 safari;
        public Opera203 opera;
        public IosSaf203 ios_saf;
        public OpMini203 op_mini;
        public Android203 android;
        public Bb203 bb;
        public OpMob203 op_mob;
        public AndChr203 and_chr;
        public AndFf203 and_ff;
        public IeMob203 ie_mob;
        public AndUc203 and_uc;

#pragma warning restore 0649

    }

}
