// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats252
    {
#pragma warning disable 0649

        public Ie253 ie;
        public Edge253 edge;
        public Firefox253 firefox;
        public Chrome253 chrome;
        public Safari253 safari;
        public Opera253 opera;
        public IosSaf253 ios_saf;
        public OpMini253 op_mini;
        public Android253 android;
        public Bb253 bb;
        public OpMob253 op_mob;
        public AndChr253 and_chr;
        public AndFf253 and_ff;
        public IeMob253 ie_mob;
        public AndUc253 and_uc;

#pragma warning restore 0649

    }

}
