// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats198
    {
#pragma warning disable 0649

        public Ie199 ie;
        public Edge199 edge;
        public Firefox199 firefox;
        public Chrome199 chrome;
        public Safari199 safari;
        public Opera199 opera;
        public IosSaf199 ios_saf;
        public OpMini199 op_mini;
        public Android199 android;
        public Bb199 bb;
        public OpMob199 op_mob;
        public AndChr199 and_chr;
        public AndFf199 and_ff;
        public IeMob199 ie_mob;
        public AndUc199 and_uc;

#pragma warning restore 0649

    }

}
