// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats50
    {
#pragma warning disable 0649

        public Ie51 ie;
        public Edge51 edge;
        public Firefox51 firefox;
        public Chrome51 chrome;
        public Safari51 safari;
        public Opera51 opera;
        public IosSaf51 ios_saf;
        public OpMini51 op_mini;
        public Android51 android;
        public Bb51 bb;
        public OpMob51 op_mob;
        public AndChr51 and_chr;
        public AndFf51 and_ff;
        public IeMob51 ie_mob;
        public AndUc51 and_uc;

#pragma warning restore 0649

    }

}
