// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats209
    {
#pragma warning disable 0649

        public Ie210 ie;
        public Edge210 edge;
        public Firefox210 firefox;
        public Chrome210 chrome;
        public Safari210 safari;
        public Opera210 opera;
        public IosSaf210 ios_saf;
        public OpMini210 op_mini;
        public Android210 android;
        public Bb210 bb;
        public OpMob210 op_mob;
        public AndChr210 and_chr;
        public AndFf210 and_ff;
        public IeMob210 ie_mob;
        public AndUc210 and_uc;

#pragma warning restore 0649

    }

}
