// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats108
    {
#pragma warning disable 0649

        public Ie109 ie;
        public Edge109 edge;
        public Firefox109 firefox;
        public Chrome109 chrome;
        public Safari109 safari;
        public Opera109 opera;
        public IosSaf109 ios_saf;
        public OpMini109 op_mini;
        public Android109 android;
        public Bb109 bb;
        public OpMob109 op_mob;
        public AndChr109 and_chr;
        public AndFf109 and_ff;
        public IeMob109 ie_mob;
        public AndUc109 and_uc;

#pragma warning restore 0649

    }

}
