// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats250
    {
#pragma warning disable 0649

        public Ie251 ie;
        public Edge251 edge;
        public Firefox251 firefox;
        public Chrome251 chrome;
        public Safari251 safari;
        public Opera251 opera;
        public IosSaf251 ios_saf;
        public OpMini251 op_mini;
        public Android251 android;
        public Bb251 bb;
        public OpMob251 op_mob;
        public AndChr251 and_chr;
        public AndFf251 and_ff;
        public IeMob251 ie_mob;
        public AndUc251 and_uc;

#pragma warning restore 0649

    }

}
