// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats167
    {
#pragma warning disable 0649

        public Ie168 ie;
        public Edge168 edge;
        public Firefox168 firefox;
        public Chrome168 chrome;
        public Safari168 safari;
        public Opera168 opera;
        public IosSaf168 ios_saf;
        public OpMini168 op_mini;
        public Android168 android;
        public Bb168 bb;
        public OpMob168 op_mob;
        public AndChr168 and_chr;
        public AndFf168 and_ff;
        public IeMob168 ie_mob;
        public AndUc168 and_uc;

#pragma warning restore 0649

    }

}
