// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats34
    {
#pragma warning disable 0649

        public Ie35 ie;
        public Edge35 edge;
        public Firefox35 firefox;
        public Chrome35 chrome;
        public Safari35 safari;
        public Opera35 opera;
        public IosSaf35 ios_saf;
        public OpMini35 op_mini;
        public Android35 android;
        public Bb35 bb;
        public OpMob35 op_mob;
        public AndChr35 and_chr;
        public AndFf35 and_ff;
        public IeMob35 ie_mob;
        public AndUc35 and_uc;

#pragma warning restore 0649

    }

}
