// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats201
    {
#pragma warning disable 0649

        public Ie202 ie;
        public Edge202 edge;
        public Firefox202 firefox;
        public Chrome202 chrome;
        public Safari202 safari;
        public Opera202 opera;
        public IosSaf202 ios_saf;
        public OpMini202 op_mini;
        public Android202 android;
        public Bb202 bb;
        public OpMob202 op_mob;
        public AndChr202 and_chr;
        public AndFf202 and_ff;
        public IeMob202 ie_mob;
        public AndUc202 and_uc;

#pragma warning restore 0649

    }

}
