// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats109
    {
#pragma warning disable 0649

        public Ie110 ie;
        public Edge110 edge;
        public Firefox110 firefox;
        public Chrome110 chrome;
        public Safari110 safari;
        public Opera110 opera;
        public IosSaf110 ios_saf;
        public OpMini110 op_mini;
        public Android110 android;
        public Bb110 bb;
        public OpMob110 op_mob;
        public AndChr110 and_chr;
        public AndFf110 and_ff;
        public IeMob110 ie_mob;
        public AndUc110 and_uc;

#pragma warning restore 0649

    }

}
