// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats242
    {
#pragma warning disable 0649

        public Ie243 ie;
        public Edge243 edge;
        public Firefox243 firefox;
        public Chrome243 chrome;
        public Safari243 safari;
        public Opera243 opera;
        public IosSaf243 ios_saf;
        public OpMini243 op_mini;
        public Android243 android;
        public Bb243 bb;
        public OpMob243 op_mob;
        public AndChr243 and_chr;
        public AndFf243 and_ff;
        public IeMob243 ie_mob;
        public AndUc243 and_uc;

#pragma warning restore 0649

    }

}
