// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats190
    {
#pragma warning disable 0649

        public Ie191 ie;
        public Edge191 edge;
        public Firefox191 firefox;
        public Chrome191 chrome;
        public Safari191 safari;
        public Opera191 opera;
        public IosSaf191 ios_saf;
        public OpMini191 op_mini;
        public Android191 android;
        public Bb191 bb;
        public OpMob191 op_mob;
        public AndChr191 and_chr;
        public AndFf191 and_ff;
        public IeMob191 ie_mob;
        public AndUc191 and_uc;

#pragma warning restore 0649

    }

}
