// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats152
    {
#pragma warning disable 0649

        public Ie153 ie;
        public Edge153 edge;
        public Firefox153 firefox;
        public Chrome153 chrome;
        public Safari153 safari;
        public Opera153 opera;
        public IosSaf153 ios_saf;
        public OpMini153 op_mini;
        public Android153 android;
        public Bb153 bb;
        public OpMob153 op_mob;
        public AndChr153 and_chr;
        public AndFf153 and_ff;
        public IeMob153 ie_mob;
        public AndUc153 and_uc;

#pragma warning restore 0649

    }

}
