// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats178
    {
#pragma warning disable 0649

        public Ie179 ie;
        public Edge179 edge;
        public Firefox179 firefox;
        public Chrome179 chrome;
        public Safari179 safari;
        public Opera179 opera;
        public IosSaf179 ios_saf;
        public OpMini179 op_mini;
        public Android179 android;
        public Bb179 bb;
        public OpMob179 op_mob;
        public AndChr179 and_chr;
        public AndFf179 and_ff;
        public IeMob179 ie_mob;
        public AndUc179 and_uc;

#pragma warning restore 0649

    }

}
