// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats160
    {
#pragma warning disable 0649

        public Ie161 ie;
        public Edge161 edge;
        public Firefox161 firefox;
        public Chrome161 chrome;
        public Safari161 safari;
        public Opera161 opera;
        public IosSaf161 ios_saf;
        public OpMini161 op_mini;
        public Android161 android;
        public Bb161 bb;
        public OpMob161 op_mob;
        public AndChr161 and_chr;
        public AndFf161 and_ff;
        public IeMob161 ie_mob;
        public AndUc161 and_uc;

#pragma warning restore 0649

    }

}
