// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats95
    {
#pragma warning disable 0649

        public Ie96 ie;
        public Edge96 edge;
        public Firefox96 firefox;
        public Chrome96 chrome;
        public Safari96 safari;
        public Opera96 opera;
        public IosSaf96 ios_saf;
        public OpMini96 op_mini;
        public Android96 android;
        public Bb96 bb;
        public OpMob96 op_mob;
        public AndChr96 and_chr;
        public AndFf96 and_ff;
        public IeMob96 ie_mob;
        public AndUc96 and_uc;

#pragma warning restore 0649

    }

}
