// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats176
    {
#pragma warning disable 0649

        public Ie177 ie;
        public Edge177 edge;
        public Firefox177 firefox;
        public Chrome177 chrome;
        public Safari177 safari;
        public Opera177 opera;
        public IosSaf177 ios_saf;
        public OpMini177 op_mini;
        public Android177 android;
        public Bb177 bb;
        public OpMob177 op_mob;
        public AndChr177 and_chr;
        public AndFf177 and_ff;
        public IeMob177 ie_mob;
        public AndUc177 and_uc;

#pragma warning restore 0649

    }

}
