// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats99
    {
#pragma warning disable 0649

        public Ie100 ie;
        public Edge100 edge;
        public Firefox100 firefox;
        public Chrome100 chrome;
        public Safari100 safari;
        public Opera100 opera;
        public IosSaf100 ios_saf;
        public OpMini100 op_mini;
        public Android100 android;
        public Bb100 bb;
        public OpMob100 op_mob;
        public AndChr100 and_chr;
        public AndFf100 and_ff;
        public IeMob100 ie_mob;
        public AndUc100 and_uc;

#pragma warning restore 0649

    }

}
