// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats171
    {
#pragma warning disable 0649

        public Ie172 ie;
        public Edge172 edge;
        public Firefox172 firefox;
        public Chrome172 chrome;
        public Safari172 safari;
        public Opera172 opera;
        public IosSaf172 ios_saf;
        public OpMini172 op_mini;
        public Android172 android;
        public Bb172 bb;
        public OpMob172 op_mob;
        public AndChr172 and_chr;
        public AndFf172 and_ff;
        public IeMob172 ie_mob;
        public AndUc172 and_uc;

#pragma warning restore 0649

    }

}
