// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats7
    {
#pragma warning disable 0649

        public Ie8 ie;
        public Edge8 edge;
        public Firefox8 firefox;
        public Chrome8 chrome;
        public Safari8 safari;
        public Opera8 opera;
        public IosSaf8 ios_saf;
        public OpMini8 op_mini;
        public Android8 android;
        public Bb8 bb;
        public OpMob8 op_mob;
        public AndChr8 and_chr;
        public AndFf8 and_ff;
        public IeMob8 ie_mob;
        public AndUc8 and_uc;

#pragma warning restore 0649

    }

}
