// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats94
    {
#pragma warning disable 0649

        public Ie95 ie;
        public Edge95 edge;
        public Firefox95 firefox;
        public Chrome95 chrome;
        public Safari95 safari;
        public Opera95 opera;
        public IosSaf95 ios_saf;
        public OpMini95 op_mini;
        public Android95 android;
        public Bb95 bb;
        public OpMob95 op_mob;
        public AndChr95 and_chr;
        public AndFf95 and_ff;
        public IeMob95 ie_mob;
        public AndUc95 and_uc;

#pragma warning restore 0649

    }

}
