// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats226
    {
#pragma warning disable 0649

        public Ie227 ie;
        public Edge227 edge;
        public Firefox227 firefox;
        public Chrome227 chrome;
        public Safari227 safari;
        public Opera227 opera;
        public IosSaf227 ios_saf;
        public OpMini227 op_mini;
        public Android227 android;
        public Bb227 bb;
        public OpMob227 op_mob;
        public AndChr227 and_chr;
        public AndFf227 and_ff;
        public IeMob227 ie_mob;
        public AndUc227 and_uc;

#pragma warning restore 0649

    }

}
