// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats134
    {
#pragma warning disable 0649

        public Ie135 ie;
        public Edge135 edge;
        public Firefox135 firefox;
        public Chrome135 chrome;
        public Safari135 safari;
        public Opera135 opera;
        public IosSaf135 ios_saf;
        public OpMini135 op_mini;
        public Android135 android;
        public Bb135 bb;
        public OpMob135 op_mob;
        public AndChr135 and_chr;
        public AndFf135 and_ff;
        public IeMob135 ie_mob;
        public AndUc135 and_uc;

#pragma warning restore 0649

    }

}
