// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats254
    {
#pragma warning disable 0649

        public Ie255 ie;
        public Edge255 edge;
        public Firefox255 firefox;
        public Chrome255 chrome;
        public Safari255 safari;
        public Opera255 opera;
        public IosSaf255 ios_saf;
        public OpMini255 op_mini;
        public Android255 android;
        public Bb255 bb;
        public OpMob255 op_mob;
        public AndChr255 and_chr;
        public AndFf255 and_ff;
        public IeMob255 ie_mob;
        public AndUc255 and_uc;

#pragma warning restore 0649

    }

}
