// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats270
    {
#pragma warning disable 0649

        public Ie271 ie;
        public Edge271 edge;
        public Firefox271 firefox;
        public Chrome271 chrome;
        public Safari271 safari;
        public Opera271 opera;
        public IosSaf271 ios_saf;
        public OpMini271 op_mini;
        public Android271 android;
        public Bb271 bb;
        public OpMob271 op_mob;
        public AndChr271 and_chr;
        public AndFf271 and_ff;
        public IeMob271 ie_mob;
        public AndUc271 and_uc;

#pragma warning restore 0649

    }

}
