// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats237
    {
#pragma warning disable 0649

        public Ie238 ie;
        public Edge238 edge;
        public Firefox238 firefox;
        public Chrome238 chrome;
        public Safari238 safari;
        public Opera238 opera;
        public IosSaf238 ios_saf;
        public OpMini238 op_mini;
        public Android238 android;
        public Bb238 bb;
        public OpMob238 op_mob;
        public AndChr238 and_chr;
        public AndFf238 and_ff;
        public IeMob238 ie_mob;
        public AndUc238 and_uc;

#pragma warning restore 0649

    }

}
