// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats141
    {
#pragma warning disable 0649

        public Ie142 ie;
        public Edge142 edge;
        public Firefox142 firefox;
        public Chrome142 chrome;
        public Safari142 safari;
        public Opera142 opera;
        public IosSaf142 ios_saf;
        public OpMini142 op_mini;
        public Android142 android;
        public Bb142 bb;
        public OpMob142 op_mob;
        public AndChr142 and_chr;
        public AndFf142 and_ff;
        public IeMob142 ie_mob;
        public AndUc142 and_uc;

#pragma warning restore 0649

    }

}
