// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats144
    {
#pragma warning disable 0649

        public Ie145 ie;
        public Edge145 edge;
        public Firefox145 firefox;
        public Chrome145 chrome;
        public Safari145 safari;
        public Opera145 opera;
        public IosSaf145 ios_saf;
        public OpMini145 op_mini;
        public Android145 android;
        public Bb145 bb;
        public OpMob145 op_mob;
        public AndChr145 and_chr;
        public AndFf145 and_ff;
        public IeMob145 ie_mob;
        public AndUc145 and_uc;

#pragma warning restore 0649

    }

}
