// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats47
    {
#pragma warning disable 0649

        public Ie48 ie;
        public Edge48 edge;
        public Firefox48 firefox;
        public Chrome48 chrome;
        public Safari48 safari;
        public Opera48 opera;
        public IosSaf48 ios_saf;
        public OpMini48 op_mini;
        public Android48 android;
        public Bb48 bb;
        public OpMob48 op_mob;
        public AndChr48 and_chr;
        public AndFf48 and_ff;
        public IeMob48 ie_mob;
        public AndUc48 and_uc;

#pragma warning restore 0649

    }

}
