// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats145
    {
#pragma warning disable 0649

        public Ie146 ie;
        public Edge146 edge;
        public Firefox146 firefox;
        public Chrome146 chrome;
        public Safari146 safari;
        public Opera146 opera;
        public IosSaf146 ios_saf;
        public OpMini146 op_mini;
        public Android146 android;
        public Bb146 bb;
        public OpMob146 op_mob;
        public AndChr146 and_chr;
        public AndFf146 and_ff;
        public IeMob146 ie_mob;
        public AndUc146 and_uc;

#pragma warning restore 0649

    }

}
