// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats73
    {
#pragma warning disable 0649

        public Ie74 ie;
        public Edge74 edge;
        public Firefox74 firefox;
        public Chrome74 chrome;
        public Safari74 safari;
        public Opera74 opera;
        public IosSaf74 ios_saf;
        public OpMini74 op_mini;
        public Android74 android;
        public Bb74 bb;
        public OpMob74 op_mob;
        public AndChr74 and_chr;
        public AndFf74 and_ff;
        public IeMob74 ie_mob;
        public AndUc74 and_uc;

#pragma warning restore 0649

    }

}
