// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats239
    {
#pragma warning disable 0649

        public Ie240 ie;
        public Edge240 edge;
        public Firefox240 firefox;
        public Chrome240 chrome;
        public Safari240 safari;
        public Opera240 opera;
        public IosSaf240 ios_saf;
        public OpMini240 op_mini;
        public Android240 android;
        public Bb240 bb;
        public OpMob240 op_mob;
        public AndChr240 and_chr;
        public AndFf240 and_ff;
        public IeMob240 ie_mob;
        public AndUc240 and_uc;

#pragma warning restore 0649

    }

}
