// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats258
    {
#pragma warning disable 0649

        public Ie259 ie;
        public Edge259 edge;
        public Firefox259 firefox;
        public Chrome259 chrome;
        public Safari259 safari;
        public Opera259 opera;
        public IosSaf259 ios_saf;
        public OpMini259 op_mini;
        public Android259 android;
        public Bb259 bb;
        public OpMob259 op_mob;
        public AndChr259 and_chr;
        public AndFf259 and_ff;
        public IeMob259 ie_mob;
        public AndUc259 and_uc;

#pragma warning restore 0649

    }

}
