// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats59
    {
#pragma warning disable 0649

        public Ie60 ie;
        public Edge60 edge;
        public Firefox60 firefox;
        public Chrome60 chrome;
        public Safari60 safari;
        public Opera60 opera;
        public IosSaf60 ios_saf;
        public OpMini60 op_mini;
        public Android60 android;
        public Bb60 bb;
        public OpMob60 op_mob;
        public AndChr60 and_chr;
        public AndFf60 and_ff;
        public IeMob60 ie_mob;
        public AndUc60 and_uc;

#pragma warning restore 0649

    }

}
