// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats149
    {
#pragma warning disable 0649

        public Ie150 ie;
        public Edge150 edge;
        public Firefox150 firefox;
        public Chrome150 chrome;
        public Safari150 safari;
        public Opera150 opera;
        public IosSaf150 ios_saf;
        public OpMini150 op_mini;
        public Android150 android;
        public Bb150 bb;
        public OpMob150 op_mob;
        public AndChr150 and_chr;
        public AndFf150 and_ff;
        public IeMob150 ie_mob;
        public AndUc150 and_uc;

#pragma warning restore 0649

    }

}
