// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats4
    {
#pragma warning disable 0649

        public Ie5 ie;
        public Edge5 edge;
        public Firefox5 firefox;
        public Chrome5 chrome;
        public Safari5 safari;
        public Opera5 opera;
        public IosSaf5 ios_saf;
        public OpMini5 op_mini;
        public Android5 android;
        public Bb5 bb;
        public OpMob5 op_mob;
        public AndChr5 and_chr;
        public AndFf5 and_ff;
        public IeMob5 ie_mob;
        public AndUc5 and_uc;

#pragma warning restore 0649

    }

}
