// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats225
    {
#pragma warning disable 0649

        public Ie226 ie;
        public Edge226 edge;
        public Firefox226 firefox;
        public Chrome226 chrome;
        public Safari226 safari;
        public Opera226 opera;
        public IosSaf226 ios_saf;
        public OpMini226 op_mini;
        public Android226 android;
        public Bb226 bb;
        public OpMob226 op_mob;
        public AndChr226 and_chr;
        public AndFf226 and_ff;
        public IeMob226 ie_mob;
        public AndUc226 and_uc;

#pragma warning restore 0649

    }

}
