// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats119
    {
#pragma warning disable 0649

        public Ie120 ie;
        public Edge120 edge;
        public Firefox120 firefox;
        public Chrome120 chrome;
        public Safari120 safari;
        public Opera120 opera;
        public IosSaf120 ios_saf;
        public OpMini120 op_mini;
        public Android120 android;
        public Bb120 bb;
        public OpMob120 op_mob;
        public AndChr120 and_chr;
        public AndFf120 and_ff;
        public IeMob120 ie_mob;
        public AndUc120 and_uc;

#pragma warning restore 0649

    }

}
