// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats264
    {
#pragma warning disable 0649

        public Ie265 ie;
        public Edge265 edge;
        public Firefox265 firefox;
        public Chrome265 chrome;
        public Safari265 safari;
        public Opera265 opera;
        public IosSaf265 ios_saf;
        public OpMini265 op_mini;
        public Android265 android;
        public Bb265 bb;
        public OpMob265 op_mob;
        public AndChr265 and_chr;
        public AndFf265 and_ff;
        public IeMob265 ie_mob;
        public AndUc265 and_uc;

#pragma warning restore 0649

    }

}
