// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats60
    {
#pragma warning disable 0649

        public Ie61 ie;
        public Edge61 edge;
        public Firefox61 firefox;
        public Chrome61 chrome;
        public Safari61 safari;
        public Opera61 opera;
        public IosSaf61 ios_saf;
        public OpMini61 op_mini;
        public Android61 android;
        public Bb61 bb;
        public OpMob61 op_mob;
        public AndChr61 and_chr;
        public AndFf61 and_ff;
        public IeMob61 ie_mob;
        public AndUc61 and_uc;

#pragma warning restore 0649

    }

}
