// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats262
    {
#pragma warning disable 0649

        public Ie263 ie;
        public Edge263 edge;
        public Firefox263 firefox;
        public Chrome263 chrome;
        public Safari263 safari;
        public Opera263 opera;
        public IosSaf263 ios_saf;
        public OpMini263 op_mini;
        public Android263 android;
        public Bb263 bb;
        public OpMob263 op_mob;
        public AndChr263 and_chr;
        public AndFf263 and_ff;
        public IeMob263 ie_mob;
        public AndUc263 and_uc;

#pragma warning restore 0649

    }

}
