// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats24
    {
#pragma warning disable 0649

        public Ie25 ie;
        public Edge25 edge;
        public Firefox25 firefox;
        public Chrome25 chrome;
        public Safari25 safari;
        public Opera25 opera;
        public IosSaf25 ios_saf;
        public OpMini25 op_mini;
        public Android25 android;
        public Bb25 bb;
        public OpMob25 op_mob;
        public AndChr25 and_chr;
        public AndFf25 and_ff;
        public IeMob25 ie_mob;
        public AndUc25 and_uc;

#pragma warning restore 0649

    }

}
