// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats87
    {
#pragma warning disable 0649

        public Ie88 ie;
        public Edge88 edge;
        public Firefox88 firefox;
        public Chrome88 chrome;
        public Safari88 safari;
        public Opera88 opera;
        public IosSaf88 ios_saf;
        public OpMini88 op_mini;
        public Android88 android;
        public Bb88 bb;
        public OpMob88 op_mob;
        public AndChr88 and_chr;
        public AndFf88 and_ff;
        public IeMob88 ie_mob;
        public AndUc88 and_uc;

#pragma warning restore 0649

    }

}
