// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats15
    {
#pragma warning disable 0649

        public Ie16 ie;
        public Edge16 edge;
        public Firefox16 firefox;
        public Chrome16 chrome;
        public Safari16 safari;
        public Opera16 opera;
        public IosSaf16 ios_saf;
        public OpMini16 op_mini;
        public Android16 android;
        public Bb16 bb;
        public OpMob16 op_mob;
        public AndChr16 and_chr;
        public AndFf16 and_ff;
        public IeMob16 ie_mob;
        public AndUc16 and_uc;

#pragma warning restore 0649

    }

}
