// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats69
    {
#pragma warning disable 0649

        public Ie70 ie;
        public Edge70 edge;
        public Firefox70 firefox;
        public Chrome70 chrome;
        public Safari70 safari;
        public Opera70 opera;
        public IosSaf70 ios_saf;
        public OpMini70 op_mini;
        public Android70 android;
        public Bb70 bb;
        public OpMob70 op_mob;
        public AndChr70 and_chr;
        public AndFf70 and_ff;
        public IeMob70 ie_mob;
        public AndUc70 and_uc;

#pragma warning restore 0649

    }

}
