// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats88
    {
#pragma warning disable 0649

        public Ie89 ie;
        public Edge89 edge;
        public Firefox89 firefox;
        public Chrome89 chrome;
        public Safari89 safari;
        public Opera89 opera;
        public IosSaf89 ios_saf;
        public OpMini89 op_mini;
        public Android89 android;
        public Bb89 bb;
        public OpMob89 op_mob;
        public AndChr89 and_chr;
        public AndFf89 and_ff;
        public IeMob89 ie_mob;
        public AndUc89 and_uc;

#pragma warning restore 0649

    }

}
