// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats72
    {
#pragma warning disable 0649

        public Ie73 ie;
        public Edge73 edge;
        public Firefox73 firefox;
        public Chrome73 chrome;
        public Safari73 safari;
        public Opera73 opera;
        public IosSaf73 ios_saf;
        public OpMini73 op_mini;
        public Android73 android;
        public Bb73 bb;
        public OpMob73 op_mob;
        public AndChr73 and_chr;
        public AndFf73 and_ff;
        public IeMob73 ie_mob;
        public AndUc73 and_uc;

#pragma warning restore 0649

    }

}
