// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats263
    {
#pragma warning disable 0649

        public Ie264 ie;
        public Edge264 edge;
        public Firefox264 firefox;
        public Chrome264 chrome;
        public Safari264 safari;
        public Opera264 opera;
        public IosSaf264 ios_saf;
        public OpMini264 op_mini;
        public Android264 android;
        public Bb264 bb;
        public OpMob264 op_mob;
        public AndChr264 and_chr;
        public AndFf264 and_ff;
        public IeMob264 ie_mob;
        public AndUc264 and_uc;

#pragma warning restore 0649

    }

}
