// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats111
    {
#pragma warning disable 0649

        public Ie112 ie;
        public Edge112 edge;
        public Firefox112 firefox;
        public Chrome112 chrome;
        public Safari112 safari;
        public Opera112 opera;
        public IosSaf112 ios_saf;
        public OpMini112 op_mini;
        public Android112 android;
        public Bb112 bb;
        public OpMob112 op_mob;
        public AndChr112 and_chr;
        public AndFf112 and_ff;
        public IeMob112 ie_mob;
        public AndUc112 and_uc;

#pragma warning restore 0649

    }

}
