// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats48
    {
#pragma warning disable 0649

        public Ie49 ie;
        public Edge49 edge;
        public Firefox49 firefox;
        public Chrome49 chrome;
        public Safari49 safari;
        public Opera49 opera;
        public IosSaf49 ios_saf;
        public OpMini49 op_mini;
        public Android49 android;
        public Bb49 bb;
        public OpMob49 op_mob;
        public AndChr49 and_chr;
        public AndFf49 and_ff;
        public IeMob49 ie_mob;
        public AndUc49 and_uc;

#pragma warning restore 0649

    }

}
