// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats82
    {
#pragma warning disable 0649

        public Ie83 ie;
        public Edge83 edge;
        public Firefox83 firefox;
        public Chrome83 chrome;
        public Safari83 safari;
        public Opera83 opera;
        public IosSaf83 ios_saf;
        public OpMini83 op_mini;
        public Android83 android;
        public Bb83 bb;
        public OpMob83 op_mob;
        public AndChr83 and_chr;
        public AndFf83 and_ff;
        public IeMob83 ie_mob;
        public AndUc83 and_uc;

#pragma warning restore 0649

    }

}
