// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats194
    {
#pragma warning disable 0649

        public Ie195 ie;
        public Edge195 edge;
        public Firefox195 firefox;
        public Chrome195 chrome;
        public Safari195 safari;
        public Opera195 opera;
        public IosSaf195 ios_saf;
        public OpMini195 op_mini;
        public Android195 android;
        public Bb195 bb;
        public OpMob195 op_mob;
        public AndChr195 and_chr;
        public AndFf195 and_ff;
        public IeMob195 ie_mob;
        public AndUc195 and_uc;

#pragma warning restore 0649

    }

}
