// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats63
    {
#pragma warning disable 0649

        public Ie64 ie;
        public Edge64 edge;
        public Firefox64 firefox;
        public Chrome64 chrome;
        public Safari64 safari;
        public Opera64 opera;
        public IosSaf64 ios_saf;
        public OpMini64 op_mini;
        public Android64 android;
        public Bb64 bb;
        public OpMob64 op_mob;
        public AndChr64 and_chr;
        public AndFf64 and_ff;
        public IeMob64 ie_mob;
        public AndUc64 and_uc;

#pragma warning restore 0649

    }

}
