// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats140
    {
#pragma warning disable 0649

        public Ie141 ie;
        public Edge141 edge;
        public Firefox141 firefox;
        public Chrome141 chrome;
        public Safari141 safari;
        public Opera141 opera;
        public IosSaf141 ios_saf;
        public OpMini141 op_mini;
        public Android141 android;
        public Bb141 bb;
        public OpMob141 op_mob;
        public AndChr141 and_chr;
        public AndFf141 and_ff;
        public IeMob141 ie_mob;
        public AndUc141 and_uc;

#pragma warning restore 0649

    }

}
