// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats291
    {
#pragma warning disable 0649

        public Ie292 ie;
        public Edge292 edge;
        public Firefox292 firefox;
        public Chrome292 chrome;
        public Safari292 safari;
        public Opera292 opera;
        public IosSaf292 ios_saf;
        public OpMini292 op_mini;
        public Android292 android;
        public Bb292 bb;
        public OpMob292 op_mob;
        public AndChr292 and_chr;
        public AndFf292 and_ff;
        public IeMob292 ie_mob;
        public AndUc292 and_uc;

#pragma warning restore 0649

    }

}
