// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats179
    {
#pragma warning disable 0649

        public Ie180 ie;
        public Edge180 edge;
        public Firefox180 firefox;
        public Chrome180 chrome;
        public Safari180 safari;
        public Opera180 opera;
        public IosSaf180 ios_saf;
        public OpMini180 op_mini;
        public Android180 android;
        public Bb180 bb;
        public OpMob180 op_mob;
        public AndChr180 and_chr;
        public AndFf180 and_ff;
        public IeMob180 ie_mob;
        public AndUc180 and_uc;

#pragma warning restore 0649

    }

}
