// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class Stats246
    {
#pragma warning disable 0649

        public Ie247 ie;
        public Edge247 edge;
        public Firefox247 firefox;
        public Chrome247 chrome;
        public Safari247 safari;
        public Opera247 opera;
        public IosSaf247 ios_saf;
        public OpMini247 op_mini;
        public Android247 android;
        public Bb247 bb;
        public OpMob247 op_mob;
        public AndChr247 and_chr;
        public AndFf247 and_ff;
        public IeMob247 ie_mob;
        public AndUc247 and_uc;

#pragma warning restore 0649

    }

}
