// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class UsageGlobal
    {
#pragma warning disable 0649

        public double 5.5;
        public double 6;
        public double 7;
        public double 8;
        public double 9;
        public double 10;
        public double 11;

#pragma warning restore 0649

    }

}
