// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class UsageGlobal9
    {
#pragma warning disable 0649

        public int 2.1;
        public int 2.2;
        public double 2.3;
        public int 3;
        public double 4;
        public double 4.1;
        public double 4.2-4.3;
        public double 4.4;
        public double 4.4.3-4.4.4;
        public int 44;

#pragma warning restore 0649

    }

}
