// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class UsageGlobal6
    {
#pragma warning disable 0649

        public double 9;
        public double 9.5-9.6;
        public double 10.0-10.1;
        public double 10.5;
        public double 10.6;
        public double 11;
        public double 11.1;
        public double 11.5;
        public double 11.6;
        public double 12;
        public double 12.1;
        public double 15;
        public double 16;
        public double 17;
        public double 18;
        public double 19;
        public double 20;
        public double 21;
        public double 22;
        public double 23;
        public double 24;
        public double 25;
        public double 26;
        public double 27;
        public double 28;
        public double 29;
        public double 30;
        public double 31;
        public int 32;
        public int 33;

#pragma warning restore 0649

    }

}
