// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class UsageGlobal5
    {
#pragma warning disable 0649

        public int 3.1;
        public double 3.2;
        public double 4;
        public double 5;
        public double 5.1;
        public double 6;
        public double 6.1;
        public double 7;
        public double 7.1;
        public double 8;
        public double 9;

#pragma warning restore 0649

    }

}
