// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class UsageGlobal4
    {
#pragma warning disable 0649

        public double 4;
        public double 5;
        public double 6;
        public double 7;
        public double 8;
        public double 9;
        public double 10;
        public double 11;
        public double 12;
        public double 13;
        public double 14;
        public double 15;
        public double 16;
        public double 17;
        public double 18;
        public double 19;
        public double 20;
        public double 21;
        public double 22;
        public double 23;
        public double 24;
        public double 25;
        public double 26;
        public double 27;
        public double 28;
        public double 29;
        public double 30;
        public double 31;
        public double 32;
        public double 33;
        public double 34;
        public double 35;
        public double 36;
        public double 37;
        public double 38;
        public double 39;
        public double 40;
        public double 41;
        public double 42;
        public double 43;
        public double 44;
        public double 45;
        public double 46;
        public int 47;
        public int 48;

#pragma warning restore 0649

    }

}
