// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class UsageGlobal11
    {
#pragma warning disable 0649

        public int 10;
        public int 11;
        public int 11.1;
        public int 11.5;
        public double 12;
        public double 12.1;
        public double 30;

#pragma warning restore 0649

    }

}
