// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class UsageGlobal7
    {
#pragma warning disable 0649

        public int 3.2;
        public int 4.0-4.1;
        public int 4.2-4.3;
        public double 5.0-5.1;
        public double 6.0-6.1;
        public double 7.0-7.1;
        public double 8;
        public double 8.1-8.4;
        public double 9;

#pragma warning restore 0649

    }

}
