// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    internal class UsageGlobal10
    {
#pragma warning disable 0649

        public double 7;
        public int 10;

#pragma warning restore 0649

    }

}
